/****** Object:  Table [dbo].[ABCBS_MADiabetesAssessment_Form]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ABCBS_MADiabetesAssessment_Form](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](30) NOT NULL,
	[FormDate] [datetime] NOT NULL,
	[FormAuthor] [varchar](100) NOT NULL,
	[CaseID] [varchar](100) NULL,
	[Version] [varchar](3) NULL,
	[docTag] [varchar](50) NULL,
	[qSelfCheckDeviceType] [varchar](max) NULL,
	[qSelfCheckDeviceBrand] [varchar](max) NULL,
	[qSelfCheckDeviceAge] [varchar](max) NULL,
	[qDoYouCheck] [varchar](max) NULL,
	[qHowOftenRecommended] [varchar](max) NULL,
	[qHowOftenReality] [varchar](max) NULL,
	[qWhyNotCheckAsRecommended] [varchar](max) NULL,
	[q2DoYouTrack] [varchar](max) NULL,
	[q2BringToDoctor] [varchar](max) NULL,
	[qHowWellControl] [varchar](max) NULL,
	[qLastA1C] [varchar](max) NULL,
	[qMedsHowToTake] [varchar](max) NULL,
	[qMedsWhatFor] [varchar](max) NULL,
	[qMedsHowOftenMiss] [varchar](max) NULL,
	[qMedsAnyDifficulty] [varchar](max) NULL,
	[qMedsHelping] [varchar](max) NULL,
	[qMedsWhyNotHelping] [varchar](max) NULL,
	[qEatHowOften] [varchar](max) NULL,
	[qEatHow] [varchar](max) NULL,
	[qSnackHowOften] [varchar](max) NULL,
	[qSnackType] [varchar](max) NULL,
	[qWaterPerDay] [varchar](max) NULL,
	[qBeveragesTypes] [varchar](max) NULL,
	[qDietEffect] [varchar](max) NULL,
	[qFoodsBeveragesToAvoid] [varchar](max) NULL,
	[qMealHowWellWorking] [varchar](max) NULL,
	[qHowFit] [varchar](max) NULL,
	[qExerciseTypes] [varchar](max) NULL,
	[qExcerciseProblems] [varchar](max) NULL,
	[qExerciseProblemsYes] [varchar](max) NULL,
	[qExcerciseMatchInterests] [varchar](max) NULL,
	[qExerciseGoals] [varchar](max) NULL,
	[qWantToImprove] [varchar](max) NULL,
	[qHowSerious] [varchar](max) NULL,
	[qImproveIn2Weeks] [varchar](max) NULL,
	[qImproveIn12Months] [varchar](max) NULL,
	[IsLocked] [varchar](max) NULL,
	[LastModifiedDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]