/****** Object:  Table [dbo].[ABCBS_MonthlyMemberOverview_Form]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ABCBS_MonthlyMemberOverview_Form](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](30) NOT NULL,
	[FormDate] [datetime] NOT NULL,
	[FormAuthor] [varchar](100) NOT NULL,
	[CaseID] [varchar](100) NULL,
	[CMCaseID] [varchar](100) NULL,
	[Version] [varchar](max) NULL,
	[PolicyEffectiveDate] [datetime] NULL,
	[PolicyTerminationDate] [datetime] NULL,
	[DateOfDeath] [datetime] NULL,
	[qGroup] [varchar](max) NULL,
	[SubscriberRelationship] [varchar](max) NULL,
	[qFormAuthor] [varchar](max) NULL,
	[ClaimsDollarsPaidToDate] [varchar](max) NULL,
	[PredictedHighCostClaimant] [varchar](max) NULL,
	[AnticipateHighCostClaimant] [varchar](max) NULL,
	[CaseProgram1] [varchar](max) NULL,
	[CMDateIdentified] [datetime] NULL,
	[CMReferralSource] [varchar](max) NULL,
	[CMReferralReason] [varchar](max) NULL,
	[CaseProgram2] [varchar](max) NULL,
	[MaternityDateIdentified] [datetime] NULL,
	[MaternityReferralSource] [varchar](max) NULL,
	[MaternityReferralReason] [varchar](max) NULL,
	[CaseProgram3] [varchar](max) NULL,
	[ClinicalSupportDateIdentified] [datetime] NULL,
	[ClinicalSupportReferralSource] [varchar](max) NULL,
	[ClinicalSupportReferralReason] [varchar](max) NULL,
	[CaseProgram4] [varchar](max) NULL,
	[ChronicCondDateIdentified] [datetime] NULL,
	[ChronicCondReferralSource] [varchar](max) NULL,
	[ChronicCondReferralReason] [varchar](max) NULL,
	[CaseProgram5] [varchar](max) NULL,
	[SWDateIdentified] [datetime] NULL,
	[SWReferralSource] [varchar](max) NULL,
	[SWReferralReason] [varchar](max) NULL,
	[ReferralCriteria] [varchar](max) NULL,
	[RiskLevel] [varchar](max) NULL,
	[RiskScore] [varchar](max) NULL,
	[PrimaryDiagDesc] [varchar](max) NULL,
	[DiagnosisEstablishedDate] [datetime] NULL,
	[BriefHistory] [varchar](max) NULL,
	[TreatmentPlan] [varchar](max) NULL,
	[AnticipatedTreatmentPlan] [varchar](max) NULL,
	[FacilityType] [varchar](max) NULL,
	[TreatmentLocation] [varchar](max) NULL,
	[Network] [varchar](max) NULL,
	[EducationalMaterials] [varchar](max) NULL,
	[TotalInboundSuccessfulCount] [varchar](max) NULL,
	[TotalOutboundSuccessfulCount] [varchar](max) NULL,
	[TotalInboundUnSuccessfulCount] [varchar](max) NULL,
	[TotalOutboundUnSuccessfulCount] [varchar](max) NULL,
	[GrandTotalContact] [varchar](max) NULL,
	[InboundSuccessfulDates] [varchar](max) NULL,
	[OutboundSuccessfulDates] [varchar](max) NULL,
	[InboundUnSuccessfulDates] [varchar](max) NULL,
	[OutboundUnSuccessfulDates] [varchar](max) NULL,
	[ClinicalIndicators] [varchar](max) NULL,
	[EvidenceBasedGuidelines] [varchar](max) NULL,
	[MedicationReconciliationDate] [datetime] NULL,
	[MedicationLists] [varchar](max) NULL,
	[DepressionScreningResults] [varchar](max) NULL,
	[DepressionScreeningCompleted] [varchar](max) NULL,
	[IncompleteCPGoals] [varchar](max) NULL,
	[TreatingPhysicians] [varchar](max) NULL,
	[MedicalDirectorConsultation] [varchar](max) NULL,
	[PharmacistConsultation] [varchar](max) NULL,
	[SocialWorkerConsultation] [varchar](max) NULL,
	[DietitianConsultation] [varchar](max) NULL,
	[SpecialtyCMConsultation] [varchar](max) NULL,
	[CaseManagementConsultation] [varchar](max) NULL,
	[TotalConsultations] [varchar](max) NULL,
	[IDTMeeting] [varchar](max) NULL,
	[CMRounds] [varchar](max) NULL,
	[CourtesyReview] [varchar](max) NULL,
	[MDFollowUp] [varchar](max) NULL,
	[PrePay] [varchar](max) NULL,
	[Appeals] [varchar](max) NULL,
	[OnSiteVisit] [varchar](max) NULL,
	[PeerToPeer] [varchar](max) NULL,
	[TotalMDActivity] [varchar](max) NULL,
	[GenMemQuestion] [varchar](max) NULL,
	[PharmacistCMRounds] [varchar](max) NULL,
	[PharmacistReferral] [varchar](max) NULL,
	[TotalPharmacistActivity] [varchar](max) NULL,
	[Intervention] [varchar](max) NULL,
	[WorkStatus] [varchar](max) NULL,
	[VendorProgramReferrals] [varchar](max) NULL,
	[Impact] [varchar](max) NULL,
	[Utilization] [varchar](max) NULL,
	[SpecialistTypes] [varchar](max) NULL,
	[IsLocked] [varchar](max) NULL,
	[LastModifiedDate] [datetime] NULL,
	[MaternityCaseID] [varchar](100) NULL,
	[ClinicalSupportCaseID] [varchar](100) NULL,
	[ChronicCondCaseID] [varchar](100) NULL,
	[SWCaseID] [varchar](100) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ABCBS_MonthlyMemberOverview_Form] ON [dbo].[ABCBS_MonthlyMemberOverview_Form]
(
	[ID] ASC
)
INCLUDE([FormDate],[IsLocked]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]