/****** Object:  Table [dbo].[ABCBS_PediatricComplexAssessment_Form]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ABCBS_PediatricComplexAssessment_Form](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](30) NOT NULL,
	[FormDate] [datetime] NOT NULL,
	[FormAuthor] [varchar](100) NOT NULL,
	[CaseID] [varchar](100) NULL,
	[qKnowledgeSkill] [varchar](max) NULL,
	[qResources] [varchar](max) NULL,
	[qSurgeries] [varchar](max) NULL,
	[qSurgeriesDescribe] [varchar](max) NULL,
	[qHealthConcerns] [varchar](max) NULL,
	[qHeartConditions] [varchar](max) NULL,
	[qHeartConditionOther] [varchar](max) NULL,
	[qSkinColorChanges] [varchar](max) NULL,
	[qSkinColorChangesDescribe] [varchar](max) NULL,
	[qSwelling] [varchar](max) NULL,
	[qSwellingReason] [varchar](max) NULL,
	[qImmunization] [varchar](max) NULL,
	[qImmunizationNeeded] [varchar](max) NULL,
	[qMusculoskeletal] [varchar](max) NULL,
	[qAbleToMoveHands] [varchar](max) NULL,
	[qAbleToMoveHandsOther] [varchar](max) NULL,
	[qAssistiveDevice] [varchar](max) NULL,
	[qSkinCondition] [varchar](max) NULL,
	[qSkinConditionDesc] [varchar](max) NULL,
	[qAnyone] [varchar](max) NULL,
	[qAnyOther] [varchar](max) NULL,
	[qENTproblems] [varchar](max) NULL,
	[qWhichProblem] [varchar](max) NULL,
	[qEyeProblem] [varchar](max) NULL,
	[qVisionProblem] [varchar](max) NULL,
	[qVisionOther] [varchar](max) NULL,
	[qEarProblem] [varchar](max) NULL,
	[qEarProblemDesc] [varchar](max) NULL,
	[qNasalProblem] [varchar](max) NULL,
	[qNasalProblem1] [varchar](max) NULL,
	[qNasalDrainagePblmOther] [varchar](max) NULL,
	[qMouthProblem] [varchar](max) NULL,
	[qCommunicationBarrier] [varchar](max) NULL,
	[qCommuicationDesc] [varchar](max) NULL,
	[qChildLearning] [varchar](max) NULL,
	[qChildLearningDesc] [varchar](max) NULL,
	[qChildBrush] [varchar](max) NULL,
	[qChildDentist] [varchar](max) NULL,
	[qGIProblem] [varchar](max) NULL,
	[qGIProblem1] [varchar](max) NULL,
	[qGIOstomy] [varchar](max) NULL,
	[qGIFeedingTube] [varchar](max) NULL,
	[qGIOther] [varchar](max) NULL,
	[qchildBowelPatterns] [varchar](max) NULL,
	[qDietPrescription] [varchar](max) NULL,
	[qDietOther] [varchar](max) NULL,
	[qEatingDisorder] [varchar](max) NULL,
	[qEatingDisorder1] [varchar](max) NULL,
	[qEatingDisorderOther] [varchar](max) NULL,
	[qWeightLoss] [varchar](max) NULL,
	[qWeightLoss1] [varchar](max) NULL,
	[q14] [varchar](max) NULL,
	[q15] [varchar](max) NULL,
	[q15a] [varchar](max) NULL,
	[q15b] [varchar](max) NULL,
	[q16] [varchar](max) NULL,
	[qUrinatingDifficulties] [varchar](max) NULL,
	[qUrinatingDifficulties1] [varchar](max) NULL,
	[qCatheter] [varchar](max) NULL,
	[qCatheter1] [varchar](max) NULL,
	[qBathroomProblems] [varchar](max) NULL,
	[qBathroomProblems1] [varchar](max) NULL,
	[qCommunityServices] [varchar](max) NULL,
	[qCommunityServices1] [varchar](max) NULL,
	[qCommunityServicesOther] [varchar](max) NULL,
	[qEmergencyNumber] [varchar](max) NULL,
	[qPrblmCarSeats] [varchar](max) NULL,
	[qHospBed] [varchar](max) NULL,
	[qStoreCleaners] [varchar](max) NULL,
	[qEmergencyPlan] [varchar](max) NULL,
	[qDiscussedwithFamily] [varchar](max) NULL,
	[qDiscussedwithFamily1] [varchar](max) NULL,
	[Comments] [varchar](max) NULL,
	[qAsthmaPlan] [varchar](max) NULL,
	[qAsthmaPlanDesc] [varchar](max) NULL,
	[qRescueMedications] [varchar](max) NULL,
	[qSignNSymptoms] [varchar](max) NULL,
	[qIrritantsTrigger] [varchar](max) NULL,
	[qPneumonia] [varchar](max) NULL,
	[qAvoidingTriggers] [varchar](max) NULL,
	[qPeakFlow] [varchar](max) NULL,
	[qDemonstrated] [varchar](max) NULL,
	[qAsthmaRescueMedi] [varchar](max) NULL,
	[qDiabetesType] [varchar](max) NULL,
	[qDiabetesType1] [varchar](max) NULL,
	[qTypeOfControl] [varchar](max) NULL,
	[qInsulin1] [varchar](max) NULL,
	[qInsulin2] [varchar](max) NULL,
	[qInsulin3] [varchar](max) NULL,
	[qInsulin4] [varchar](max) NULL,
	[qEduOnDiabetes] [varchar](max) NULL,
	[qTellMeChildDiabetes] [varchar](max) NULL,
	[qA1c] [varchar](max) NULL,
	[qA1cresult] [varchar](max) NULL,
	[qA1cRanges] [varchar](max) NULL,
	[qA1cActions] [varchar](max) NULL,
	[qA1cActionsOther] [varchar](max) NULL,
	[qDayCareDiabetesPlan] [varchar](max) NULL,
	[qSchoolMissed] [varchar](max) NULL,
	[qSickDayPlan] [varchar](max) NULL,
	[qDiabetesID] [varchar](max) NULL,
	[qBloodSUgar] [varchar](max) NULL,
	[qbloodSugarOther] [varchar](max) NULL,
	[qBloodSUgaratHome] [varchar](max) NULL,
	[qBloodSUgaratHomeOther] [varchar](max) NULL,
	[qRangeofBloodSugar] [varchar](max) NULL,
	[qHighBloodSugar] [varchar](max) NULL,
	[qlowBloodSugar] [varchar](max) NULL,
	[qchildExamFeet] [varchar](max) NULL,
	[qDilatedEyeExam] [varchar](max) NULL,
	[qChildBP] [varchar](max) NULL,
	[qUrineTest] [varchar](max) NULL,
	[qMicroalbumiburia] [varchar](max) NULL,
	[qHighLipids] [varchar](max) NULL,
	[qHDLValue] [varchar](max) NULL,
	[qLDLValue] [varchar](max) NULL,
	[qCholestrolLevel] [varchar](max) NULL,
	[qScale1] [varchar](max) NULL,
	[qScale2] [varchar](max) NULL,
	[qScale3] [varchar](max) NULL,
	[LastModifiedDate] [datetime] NULL,
	[IsLocked] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ABCBS_PediatricComplexAssessment_Form] ON [dbo].[ABCBS_PediatricComplexAssessment_Form]
(
	[ID] ASC
)
INCLUDE([FormDate],[IsLocked]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ABCBS_PediatricComplexAssessment_Form_FormDate] ON [dbo].[ABCBS_PediatricComplexAssessment_Form]
(
	[FormDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[ABCBS_PediatricComplexAssessment_Form] ADD  DEFAULT (getdate()) FOR [LastModifiedDate]