/****** Object:  Table [dbo].[ABCBS_HEP_AdultEnrollment_Form]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ABCBS_HEP_AdultEnrollment_Form](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](30) NOT NULL,
	[FormDate] [datetime] NOT NULL,
	[FormAuthor] [varchar](100) NOT NULL,
	[CaseID] [varchar](100) NULL,
	[q1ReferralSource] [varchar](max) NULL,
	[q1aOtherSource] [varchar](max) NULL,
	[q2Program] [varchar](max) NULL,
	[q3WorkDays] [varchar](max) NULL,
	[q3PneumoniaShot] [varchar](max) NULL,
	[q4FluShot] [varchar](max) NULL,
	[q14] [varchar](max) NULL,
	[q15] [varchar](max) NULL,
	[q15a] [varchar](max) NULL,
	[q15b] [varchar](max) NULL,
	[q16] [varchar](max) NULL,
	[q16Nutrition] [varchar](max) NULL,
	[q9Exercise] [varchar](max) NULL,
	[q10ExerciseDays] [varchar](max) NULL,
	[q11ExerciseTolerated] [varchar](max) NULL,
	[q12FoodDiet] [varchar](max) NULL,
	[q13Tobacco] [varchar](max) NULL,
	[q14HistoryNicotine] [varchar](max) NULL,
	[q15ERVisit] [varchar](max) NULL,
	[q16Admit] [varchar](max) NULL,
	[q17LBPOrigCaseFindDate] [datetime] NULL,
	[q18LBPCaseFindDate] [datetime] NULL,
	[q19LBPEnrollDate] [datetime] NULL,
	[q20DailyActivities] [varchar](max) NULL,
	[q21PainFrequency] [varchar](max) NULL,
	[q22PainDuration] [varchar](max) NULL,
	[q23PainSeverity] [varchar](max) NULL,
	[q24LBPSelfManage] [varchar](max) NULL,
	[q25DiabetesOrigCaseFindDate] [datetime] NULL,
	[q26DiabetesCaseFindDate] [datetime] NULL,
	[q27DiabetesPEnrollDate] [datetime] NULL,
	[q28DiabetesHowLong] [varchar](max) NULL,
	[q29DiabetesTreatment] [varchar](max) NULL,
	[q30GlucoseTest] [varchar](max) NULL,
	[q31ERDiabetes] [varchar](max) NULL,
	[q32FootProblem] [varchar](max) NULL,
	[q33FastingRead] [varchar](max) NULL,
	[q34HgbA1c] [varchar](max) NULL,
	[q35InfoOnDiabetes] [varchar](max) NULL,
	[q36AsthmaOrigCaseFindDate] [datetime] NULL,
	[q37AsthmaCaseFindDate] [datetime] NULL,
	[q37AsthmaPEnrollDate] [datetime] NULL,
	[q38AsthmaChestTightHowLong] [varchar](max) NULL,
	[q39Asthma4weekControl] [varchar](max) NULL,
	[q40Asthma4weekWakeUp] [varchar](max) NULL,
	[q41Asthma4weekQuickRelief] [varchar](max) NULL,
	[q42AsthmaInhalerSpacer] [varchar](max) NULL,
	[q43Asthma4WeekDailyActivity] [varchar](max) NULL,
	[q44AsthmaDaysWorkMissed] [varchar](max) NULL,
	[q45AsthmaActionPlan] [varchar](max) NULL,
	[q46AsthmaTriggers] [varchar](max) NULL,
	[q46aOtherTrigger] [varchar](max) NULL,
	[q47AsthmaTreatment] [varchar](max) NULL,
	[q48InfoOnAsthma] [varchar](max) NULL,
	[q49CardioOrigCaseFindDate] [datetime] NULL,
	[q50CardioCaseFindDate] [datetime] NULL,
	[q51CardioPEnrollDate] [datetime] NULL,
	[q52CardioHighBP] [varchar](max) NULL,
	[q53CardioHighBPHowLong] [varchar](max) NULL,
	[q54CardioCholesterol] [varchar](max) NULL,
	[q55CardioHighCholesterolHowLong] [varchar](max) NULL,
	[q56CardioDxHeartAttack] [varchar](max) NULL,
	[q57CardioDxStentReplacement] [varchar](max) NULL,
	[q58CardioDxAngina] [varchar](max) NULL,
	[q59CardioDxAngioplasty] [varchar](max) NULL,
	[q60CardioDxCVD] [varchar](max) NULL,
	[q61CardioDxBypass] [varchar](max) NULL,
	[q62CardioDxNotListed] [varchar](max) NULL,
	[q63CardioTreatment] [varchar](max) NULL,
	[q64CardioLastMonthExperience] [varchar](max) NULL,
	[q65CardioBPRxHowLong] [varchar](max) NULL,
	[q66CardioCholesterolRxHowLong] [varchar](max) NULL,
	[q67CardioSystolic] [varchar](max) NULL,
	[q68CardioDiastolic] [varchar](max) NULL,
	[q69CardioKnowBP] [varchar](max) NULL,
	[q70CardioDxDiabeted] [varchar](max) NULL,
	[q71CardioMoreInfo] [varchar](max) NULL,
	[q72CHFOrigCaseFindDate] [datetime] NULL,
	[q73CHFCaseFindDate] [datetime] NULL,
	[q74CHFPEnrollDate] [datetime] NULL,
	[q75CHFTreatment] [varchar](max) NULL,
	[q76CHFCallsProvider] [varchar](max) NULL,
	[q77CHFCall911] [varchar](max) NULL,
	[q78CHFMoreInfo] [varchar](max) NULL,
	[q78COPDOrigCaseFindDate] [datetime] NULL,
	[q79COPDCaseFindDate] [datetime] NULL,
	[q80COPDPEnrollDate] [datetime] NULL,
	[q81COPDBreathAtRest] [varchar](max) NULL,
	[q82COPDInControl] [varchar](max) NULL,
	[q83COPDcough] [varchar](max) NULL,
	[q84COPDmucus] [varchar](max) NULL,
	[q85COPDtightchest] [varchar](max) NULL,
	[q86COPDbreathless] [varchar](max) NULL,
	[q87COPDlimitactivity] [varchar](max) NULL,
	[q88COPDleavinghome] [varchar](max) NULL,
	[q89COPDsleep] [varchar](max) NULL,
	[q90COPDenergy] [varchar](max) NULL,
	[q91COPDTreatment] [varchar](max) NULL,
	[q92COPDMoreInfo] [varchar](max) NULL,
	[q93HWOrigCaseFindDate] [datetime] NULL,
	[q94HWCaseFindDate] [datetime] NULL,
	[q95HWPEnrollDate] [datetime] NULL,
	[q96WeightTarget] [varchar](max) NULL,
	[q97HWLoseReason] [varchar](max) NULL,
	[q98HWFamilyHistory] [varchar](max) NULL,
	[q99HWPersonalHistory] [varchar](max) NULL,
	[q100HWLoseTry] [varchar](max) NULL,
	[q101LoseSuccess] [varchar](max) NULL,
	[q102LoseReadiness] [varchar](max) NULL,
	[q103HWMoreInfo] [varchar](max) NULL,
	[TotalScore] [varchar](max) NULL,
	[q104Comment] [varchar](max) NULL,
	[LastModifiedDate] [datetime] NULL,
	[IsLocked] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ABCBS_HEP_AdultEnrollment_Form] ON [dbo].[ABCBS_HEP_AdultEnrollment_Form]
(
	[ID] ASC
)
INCLUDE([FormDate],[IsLocked]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ABCBS_HEP_AdultEnrollment_Form_FormDate] ON [dbo].[ABCBS_HEP_AdultEnrollment_Form]
(
	[FormDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[ABCBS_HEP_AdultEnrollment_Form] ADD  DEFAULT (getdate()) FOR [LastModifiedDate]