/****** Object:  Table [dbo].[ARBCBS_MemberAlert]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARBCBS_MemberAlert](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](20) NOT NULL,
	[CustID] [int] NULL,
	[UserName] [varchar](20) NOT NULL,
	[ProductID] [int] NOT NULL,
	[PersonalHarm] [bit] NULL,
	[PHComment] [varchar](max) NULL,
	[PHDate] [datetime] NULL,
	[PermissionToSpeak] [bit] NULL,
	[PermToSpeakComment] [varchar](max) NULL,
	[PermToSpeakDate] [datetime] NULL,
	[LangPreference] [bit] NULL,
	[LangPrefComment] [varchar](max) NULL,
	[LangPrefDate] [datetime] NULL,
	[Other1] [bit] NULL,
	[Other1Comment] [varchar](max) NULL,
	[OtherDate1] [datetime] NULL,
	[Other2] [bit] NULL,
	[Other2Comment] [varchar](max) NULL,
	[OtherDate2] [datetime] NULL,
	[Other3] [bit] NULL,
	[Other3Comment] [varchar](max) NULL,
	[OtherDate3] [datetime] NULL,
	[Other4] [bit] NULL,
	[Other4Comment] [varchar](max) NULL,
	[OtherDate4] [datetime] NULL,
	[Other5] [bit] NULL,
	[Other5Comment] [varchar](max) NULL,
	[OtherDate5] [datetime] NULL,
	[OtherCount] [int] NULL,
	[Other1Delete] [bit] NULL,
	[Other2Delete] [bit] NULL,
	[Other3Delete] [bit] NULL,
	[Other4Delete] [bit] NULL,
	[Other5Delete] [bit] NULL,
	[GrpInitiativeWQI] [varchar](30) NULL,
	[GrpInitiativeWQIDate] [datetime] NULL,
	[GrpInitiativeWQIComment] [varchar](max) NULL,
	[GrpInitiativeGR] [varchar](30) NULL,
	[GrpInitiativeGRDate] [datetime] NULL,
	[GrpInitiativeGRComment] [varchar](max) NULL,
	[CreatedDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]