/****** Object:  Table [dbo].[ARBCBS_Contact_Form]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARBCBS_Contact_Form](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](20) NOT NULL,
	[FormDate] [datetime] NOT NULL,
	[FormAuthor] [varchar](100) NOT NULL,
	[CaseID] [varchar](100) NULL,
	[q1ContactDate] [datetime] NULL,
	[q2program] [varchar](max) NULL,
	[q3ContactType] [varchar](max) NULL,
	[q4ContactType] [varchar](max) NULL,
	[qMemberContactedToday] [varchar](max) NULL,
	[q5ContactMethod] [varchar](max) NULL,
	[q6SiteOfVist] [varchar](max) NULL,
	[q6PhnNumber] [varchar](max) NULL,
	[q7ContactSuccess] [varchar](max) NULL,
	[q8ContactReason] [varchar](max) NULL,
	[q9VendorsDiscussed] [varchar](max) NULL,
	[q110VendorsDiscussed1] [varchar](max) NULL,
	[q1SocialWork] [varchar](max) NULL,
	[SWComment] [varchar](max) NULL,
	[q1SpecialityCare] [varchar](max) NULL,
	[SCMProgramType] [varchar](max) NULL,
	[q2CDM] [varchar](max) NULL,
	[q3CDM] [varchar](max) NULL,
	[q4CDM] [varchar](max) NULL,
	[DietitianActionTaken] [varchar](max) NULL,
	[CDMComment] [varchar](max) NULL,
	[q1HEP] [varchar](max) NULL,
	[q2HEP] [varchar](max) NULL,
	[q3HEP] [varchar](max) NULL,
	[q4HEP] [varchar](max) NULL,
	[q5HEP] [varchar](max) NULL,
	[HEPComment] [varchar](max) NULL,
	[q1ClinicSup] [varchar](max) NULL,
	[q1Disability] [varchar](max) NULL,
	[q2Disability] [datetime] NULL,
	[q3Disability] [varchar](max) NULL,
	[q4Disability] [datetime] NULL,
	[q5Disability] [varchar](max) NULL,
	[q6Disability] [varchar](max) NULL,
	[q1Discharge] [datetime] NULL,
	[q2Discharge] [varchar](max) NULL,
	[q3Discharge] [datetime] NULL,
	[q4Discharge] [varchar](max) NULL,
	[q5Discharge] [varchar](max) NULL,
	[q6Discharge] [varchar](max) NULL,
	[q7Discharge] [datetime] NULL,
	[q8Discharge] [varchar](max) NULL,
	[q9Discharge] [varchar](max) NULL,
	[CSComment] [varchar](max) NULL,
	[qMaternityMember] [varchar](max) NULL,
	[qMaternityMomDueDate] [datetime] NULL,
	[qMaternityCallType] [varchar](max) NULL,
	[qMaternityProblems] [varchar](max) NULL,
	[qUterineContractions] [varchar](max) NULL,
	[qMaternitySymptoms] [varchar](max) NULL,
	[qMaternityOther] [varchar](max) NULL,
	[qMemberMailing] [varchar](max) NULL,
	[qLastDoctorVisit] [datetime] NULL,
	[qbabyCallType] [varchar](max) NULL,
	[qMemMailing] [varchar](max) NULL,
	[qbabyGestational] [varchar](max) NULL,
	[qbabyBirthWeight] [varchar](max) NULL,
	[qbabyCurentWeight] [varchar](max) NULL,
	[qO2Needs] [varchar](max) NULL,
	[qBedType] [varchar](max) NULL,
	[qBabyFeed] [varchar](max) NULL,
	[qVolumeOfFeed] [varchar](max) NULL,
	[qBabyFormulaorBreastMilk] [varchar](max) NULL,
	[qBabyTests] [varchar](max) NULL,
	[qBabyTestsOther] [varchar](max) NULL,
	[qTransfusions] [varchar](max) NULL,
	[qLines] [varchar](max) NULL,
	[qLinesOther] [varchar](max) NULL,
	[qBabyLastVisit] [datetime] NULL,
	[qBabyImmunization] [varchar](max) NULL,
	[qBabySeries] [varchar](max) NULL,
	[qBabySeriesOther] [varchar](max) NULL,
	[qBabySeries2] [varchar](max) NULL,
	[qBabySeriesOther2] [varchar](max) NULL,
	[qBabySeries4] [varchar](max) NULL,
	[qBabySeriesOther4] [varchar](max) NULL,
	[qBabySeries6] [varchar](max) NULL,
	[qBabySeriesOther6] [varchar](max) NULL,
	[qBabySeries12] [varchar](max) NULL,
	[qBabySeriesOther12] [varchar](max) NULL,
	[qBabyDiagnosed] [varchar](max) NULL,
	[qBabyDiagnosed1] [varchar](max) NULL,
	[qNCSComment] [varchar](max) NULL,
	[qCMComment] [varchar](max) NULL,
	[qMaternityMomComment] [varchar](max) NULL,
	[qMaternityBabyComment] [varchar](max) NULL,
	[q5ReturnCall] [varchar](max) NULL,
	[qOtherContact] [varchar](max) NULL,
	[qFEPLetterSent] [varchar](max) NULL,
	[qMedAdvLetterSent] [varchar](max) NULL,
	[qOtherContactOther] [varchar](max) NULL,
	[qFEPShortTermInterventions] [varchar](max) NULL,
	[qDepartment] [varchar](max) NULL,
	[qSavingsAmount] [varchar](max) NULL,
	[shortTermIntervention] [varchar](max) NULL,
	[qSTIntervntnOther] [varchar](max) NULL,
	[FEPDiseaseMgmnt] [varchar](max) NULL,
	[FEPDiseaseMngmtContactDate] [datetime] NULL,
	[FEPDiseaseMngmtContactTime] [varchar](max) NULL,
	[qMemberGiveConsent] [varchar](max) NULL,
	[FEPDiseaseMngmtConsentDate] [datetime] NULL,
	[qActivityCondition] [varchar](max) NULL,
	[MedicationComplianceAssessed] [varchar](max) NULL,
	[qExcludePrograms] [varchar](max) NULL,
	[qHEPSpanishMaterials] [varchar](max) NULL,
	[qNetworkProvider] [varchar](max) NULL,
	[q4Covid] [varchar](max) NULL,
	[LastModifiedDate] [datetime] NULL,
	[qInboundCustomerService] [varchar](max) NULL,
	[qPharmacyComment] [varchar](max) NULL,
	[Version] [varchar](max) NULL,
	[IsLocked] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ARBCBS_Contact_Form] ON [dbo].[ARBCBS_Contact_Form]
(
	[ID] ASC
)
INCLUDE([FormDate],[IsLocked]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ARBCBS_Contact_Form_FormDate] ON [dbo].[ARBCBS_Contact_Form]
(
	[FormDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_ARBCBS_Contact_Form_MVDID_ContactDate] ON [dbo].[ARBCBS_Contact_Form]
(
	[MVDID] ASC
)
INCLUDE([q1ContactDate]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85) ON [PRIMARY]
ALTER TABLE [dbo].[ARBCBS_Contact_Form] ADD  DEFAULT (getdate()) FOR [LastModifiedDate]