/****** Object:  Table [dbo].[ElixMemberRisk]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ElixMemberRisk](
	[MVDID] [varchar](20) NOT NULL,
	[MonthID] [varchar](6) NULL,
	[Elixhauser_Score] [int] NULL,
	[GroupID] [int] NULL,
	[Createdate] [datetime] NULL,
	[Updatedate] [datetime] NULL,
	[RecordNumber] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_ElixMemberRisk] PRIMARY KEY CLUSTERED 
(
	[RecordNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IC_ElixMemberRisk_MVDID] ON [dbo].[ElixMemberRisk]
(
	[MVDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_ElixMemberRisk_MonthID_MVDID_GroupID] ON [dbo].[ElixMemberRisk]
(
	[MonthID] ASC,
	[MVDID] ASC,
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]