/****** Object:  Table [dbo].[Final_HEDIS_Member]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Final_HEDIS_Member](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](50) NULL,
	[MemberID] [varchar](50) NULL,
	[IsTestDue] [int] NULL,
	[TestID] [int] NULL,
	[DoctorUserName] [varchar](50) NULL,
	[CustID] [int] NULL,
	[PCP_NPI] [varchar](50) NULL,
	[PCP_TIN] [varchar](50) NULL,
	[LOB] [varchar](20) NULL,
	[SDA] [varchar](100) NULL,
	[MemberFirstName] [varchar](50) NULL,
	[MemberLastName] [varchar](50) NULL,
	[HasAsthma] [char](1) NULL,
	[HasDiabetes] [char](1) NULL,
	[RemindInDays] [int] NULL,
	[ERVisitCount] [int] NULL,
	[NoteCount] [int] NULL,
	[MeasureNote] [varchar](max) NULL,
	[MonthID] [char](6) NULL,
	[W15_VisitCount] [int] NULL,
	[Created] [datetime] NULL,
	[DOB] [date] NULL,
 CONSTRAINT [PK_Final_HEDIS_Member_Temp] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_10] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC,
	[PCP_TIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_11] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC,
	[PCP_TIN] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_12] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC,
	[LOB] ASC,
	[PCP_NPI] ASC,
	[PCP_TIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_13] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC,
	[LOB] ASC,
	[PCP_NPI] ASC,
	[PCP_TIN] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_2] ON [dbo].[Final_HEDIS_Member]
(
	[MVDID] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_3] ON [dbo].[Final_HEDIS_Member]
(
	[MVDID] ASC,
	[CustID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_5] ON [dbo].[Final_HEDIS_Member]
(
	[PCP_TIN] ASC,
	[TestID] ASC,
	[MonthID] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_6] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_9] ON [dbo].[Final_HEDIS_Member]
(
	[CustID] ASC,
	[TestID] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_Temp_MemberID] ON [dbo].[Final_HEDIS_Member]
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_TestID_CustID] ON [dbo].[Final_HEDIS_Member]
(
	[TestID] ASC,
	[CustID] ASC
)
INCLUDE([MVDID],[MemberID],[IsTestDue],[PCP_NPI],[PCP_TIN],[LOB],[MemberFirstName],[MemberLastName],[HasAsthma],[HasDiabetes],[MeasureNote],[DOB]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[Final_HEDIS_Member] ADD  CONSTRAINT [DF_Final_HEDIS_Member_Temp_Created]  DEFAULT (getdate()) FOR [Created]