/****** Object:  Table [dbo].[Final_HEDIS_Member_FULL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Final_HEDIS_Member_FULL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](50) NULL,
	[MemberID] [varchar](50) NULL,
	[DOB] [date] NULL,
	[IsTestDue] [int] NULL,
	[TestID] [int] NULL,
	[DoctorUserName] [varchar](50) NULL,
	[CustID] [int] NULL,
	[PCP_NPI] [varchar](50) NULL,
	[PCP_TIN] [varchar](50) NULL,
	[LOB] [varchar](20) NULL,
	[SDA] [varchar](100) NULL,
	[MemberFirstName] [varchar](50) NULL,
	[MemberLastName] [varchar](50) NULL,
	[HasAsthma] [char](1) NULL,
	[HasDiabetes] [char](1) NULL,
	[RemindInDays] [int] NULL,
	[ERVisitCount] [int] NULL,
	[NoteCount] [int] NULL,
	[MeasureNote] [varchar](max) NULL,
	[MonthID] [char](6) NULL,
	[W15_VisitCount] [int] NULL,
	[Created] [datetime] NULL,
 CONSTRAINT [PK_Final_HEDIS_Member_FULL_Temp] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_CustID_TestID_MonthID] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[TestID] ASC,
	[MonthID] ASC
)
INCLUDE([IsTestDue]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_CustID_PCP_TIN] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[PCP_TIN] ASC
)
INCLUDE([PCP_NPI],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[MonthID] ASC,
	[PCP_TIN] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_11] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[MonthID] ASC,
	[CustID] ASC,
	[TestID] ASC,
	[LOB] ASC,
	[PCP_NPI] ASC,
	[PCP_TIN] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_13] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[MonthID] ASC,
	[CustID] ASC,
	[TestID] ASC,
	[PCP_TIN] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_16] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[MVDID] ASC,
	[MonthID] ASC
)
INCLUDE([TestID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_2] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[MonthID] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_4] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[IsTestDue] ASC,
	[PCP_NPI] ASC,
	[MonthID] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_5] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[CustID] ASC,
	[TestID] ASC,
	[IsTestDue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_IsTestDue_TestID_CustID_PCP_TIN] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[IsTestDue] ASC,
	[TestID] ASC,
	[CustID] ASC,
	[PCP_TIN] ASC
)
INCLUDE([MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_Temp_TestID_CustID] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[TestID] ASC,
	[CustID] ASC,
	[PCP_NPI] ASC
)
INCLUDE([MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Final_HEDIS_Member_FULL_TestID_CustID] ON [dbo].[Final_HEDIS_Member_FULL]
(
	[TestID] ASC,
	[CustID] ASC,
	[PCP_TIN] ASC
)
INCLUDE([IsTestDue],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[Final_HEDIS_Member_FULL] ADD  CONSTRAINT [DF_Final_HEDIS_Member_FULL_Temp_Created]  DEFAULT (getdate()) FOR [Created]