/****** Object:  Table [dbo].[FinalCovidMemberNWC]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FinalCovidMemberNWC](
	[MemberID] [varchar](15) NULL,
	[State] [varchar](2) NULL,
	[City] [varchar](50) NULL,
	[countyname] [varchar](30) NULL,
	[Zipcode] [varchar](9) NULL,
	[SubscriberID] [varchar](10) NULL,
	[CmOrgRegion] [varchar](50) NULL,
	[LOB] [varchar](2) NULL,
	[Relationship] [varchar](2) NULL,
	[MVDID] [varchar](30) NULL,
	[ClaimNumber] [varchar](20) NULL,
	[StatementFromDate] [date] NULL,
	[Code] [varchar](10) NULL,
	[TypeOfDiag] [varchar](5) NULL,
	[RiskGroupID] [int] NULL,
	[MemberFirstName] [varchar](50) NULL,
	[MemberLastName] [varchar](50) NULL,
	[Age] [int] NULL,
	[Sex] [varchar](1) NULL,
	[EmergencyIndicator] [bit] NULL,
	[NetworkIndicator] [varchar](1) NULL,
	[AdmissionDate] [datetime] NULL,
	[DischargeDate] [datetime] NULL,
	[DischargeStatusCode] [varchar](2) NULL,
	[BilledAmount] [decimal](18, 2) NULL,
	[ClaimStatus] [varchar](5) NULL,
	[FacilityTIN] [varchar](10) NULL,
	[PartyKey] [int] NULL,
	[Cond1] [varchar](1) NULL,
	[Cond2] [varchar](1) NULL,
	[Cond3] [varchar](1) NULL,
	[Cond4] [varchar](1) NULL,
	[Cond5] [varchar](1) NULL,
	[Cond6] [varchar](1) NULL,
	[Cond7] [varchar](1) NULL,
	[Cond8] [varchar](1) NULL,
	[Cond9] [varchar](1) NULL,
	[Cond10] [varchar](1) NULL,
	[Cond11] [varchar](1) NULL,
	[Cond12] [varchar](1) NULL,
	[Cond13] [varchar](1) NULL,
	[Cond14] [varchar](1) NULL,
	[Cond15] [varchar](1) NULL,
	[Cond16] [varchar](1) NULL,
	[Cond17] [varchar](1) NULL,
	[Cond18] [varchar](1) NULL,
	[Cond19] [varchar](1) NULL,
	[Cond20] [varchar](1) NULL,
	[Cond21] [varchar](1) NULL,
	[Cond22] [varchar](1) NULL,
	[Cond23] [varchar](1) NULL,
	[Cond24] [varchar](1) NULL,
	[Cond25] [varchar](1) NULL,
	[Cond26] [varchar](1) NULL,
	[Cond27] [varchar](1) NULL,
	[Cond28] [varchar](1) NULL,
	[Cond29] [varchar](1) NULL,
	[Cond30] [varchar](1) NULL,
	[Cond31] [varchar](1) NULL,
	[Loaddate] [date] NULL
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_FinalCovidMemberNWC_Loaddate] ON [dbo].[FinalCovidMemberNWC]
(
	[Loaddate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]