/****** Object:  Table [dbo].[FinalMemberTemporary]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FinalMemberTemporary](
	[RecordID] [bigint] IDENTITY(1,1) NOT NULL,
	[MVDID] [varchar](30) NOT NULL,
	[MemberID] [varchar](15) NULL,
	[MemberFirstName] [varchar](50) NULL,
	[MemberLastName] [varchar](50) NULL,
	[MemberMiddleName] [varchar](50) NULL,
	[Gender] [varchar](1) NULL,
	[DateOfBirth] [date] NULL,
	[SSN] [varchar](9) NULL,
	[Relationship] [varchar](2) NULL,
	[SubscriberID] [varchar](10) NULL,
	[Address1] [varchar](100) NULL,
	[Address2] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](2) NULL,
	[Zipcode] [varchar](9) NULL,
	[Race] [varchar](2) NULL,
	[Ethnicity] [varchar](2) NULL,
	[CurrentCoPayLevel] [varchar](1) NULL,
	[Suffix] [varchar](15) NULL,
	[HomePhone] [varchar](10) NULL,
	[WorkPhone] [varchar](14) NULL,
	[Fax] [varchar](10) NULL,
	[Email] [varchar](100) NULL,
	[Language] [varchar](50) NULL,
	[SpokenLanguage] [varchar](50) NULL,
	[WrittenLanguage] [varchar](50) NULL,
	[OtherLanguage] [varchar](50) NULL,
	[DentalBenefit] [varchar](1) NULL,
	[DrugBenefit] [varchar](1) NULL,
	[MentalHealthBenefitInpatient] [varchar](1) NULL,
	[MentalHealthBenefitIntensiveOutpatient] [varchar](1) NULL,
	[MentalHealthBenefitOutpatientED] [varchar](1) NULL,
	[ChemicalDependencyBenefitInpatient] [varchar](1) NULL,
	[ChemicalDependencyBenefitIntensiveOutpatient] [varchar](1) NULL,
	[ChemicalDependencyBenefitOutpatientED] [varchar](1) NULL,
	[HospiceBenefit] [varchar](1) NULL,
	[HealthPlanEmployeeFlag] [varchar](1) NULL,
	[MaritalStatus] [varchar](1) NULL,
	[HeightInches] [varchar](5) NULL,
	[WeightLbs] [varchar](6) NULL,
	[CustID] [int] NULL,
	[BaseBatchID] [bigint] NULL,
	[CurrentBatchID] [bigint] NULL,
	[MemberKey] [int] NULL,
	[CompanyKey] [int] NULL,
	[PartyKey] [int] NULL,
	[SubgroupKey] [int] NULL,
	[PlanGroup] [int] NULL,
	[BrandingName] [varchar](50) NULL,
	[CmOrgRegion] [varchar](50) NULL,
	[AssociatedMemberID] [varchar](15) NULL,
	[LOB] [varchar](255) NULL,
	[CreatedBy] [varchar](255) NULL,
	[Createddate] [datetime] NULL,
	[LastModifiedBy] [varchar](255) NULL,
	[LastModifiedDate] [datetime] NULL,
 CONSTRAINT [PK__FinalMem__1A181306092FC91D] PRIMARY KEY CLUSTERED 
(
	[MVDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]