/****** Object:  Table [dbo].[Link_LegacyMemberId_MVD_Ins]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Link_LegacyMemberId_MVD_Ins](
	[MVDId] [varchar](30) NOT NULL,
	[InsMemberId] [varchar](20) NOT NULL,
	[Cust_ID] [int] NOT NULL,
	[Created] [datetime] NULL,
	[IsPrimary] [bit] NULL,
	[Active] [bit] NULL,
	[IsArchived] [bit] NULL,
	[ArchivedDate] [datetime] NULL,
	[ArchiveAttemptCount] [int] NULL,
	[System_Memid] [varchar](30) NULL,
 CONSTRAINT [PK_Link_MemberId_MVD_Ins] PRIMARY KEY CLUSTERED 
(
	[MVDId] ASC,
	[InsMemberId] ASC,
	[Cust_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [IX_Link_MemberId_MVD_Ins] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[InsMemberId] ASC,
	[Cust_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Link_MemberId_MVD_Ins_1] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[MVDId] ASC,
	[InsMemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Link_MemberId_MVD_Ins_2] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[InsMemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_Link_MemberId_MVD_Ins_Cust_ID_MVDId_InsMemberId] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[Cust_ID] ASC
)
INCLUDE([MVDId],[InsMemberId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Link_MemberId_MVD_Ins_MVDID] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[MVDId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [MVDId_InsMemberId] ON [dbo].[Link_LegacyMemberId_MVD_Ins]
(
	[IsPrimary] ASC
)
INCLUDE([MVDId],[InsMemberId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] ADD  CONSTRAINT [DF_Link_MemberId_MVD_Ins_Created]  DEFAULT (getutcdate()) FOR [Created]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] ADD  CONSTRAINT [DF_Link_MemberId_MVD_Ins_IsPrimary]  DEFAULT ((1)) FOR [IsPrimary]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] ADD  CONSTRAINT [DF__Link_Memb__Activ__4FDD8E17]  DEFAULT ((1)) FOR [Active]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] ADD  CONSTRAINT [DF__Link_Memb__IsArc__53AE1EFB]  DEFAULT ((0)) FOR [IsArchived]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] ADD  CONSTRAINT [DF__Link_Memb__Archi__54A24334]  DEFAULT ((0)) FOR [ArchiveAttemptCount]
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins]  WITH CHECK ADD  CONSTRAINT [FK_Link_MemberId_MVD_Ins_HPCustomer] FOREIGN KEY([Cust_ID])
REFERENCES [dbo].[HPCustomer] ([Cust_ID])
ALTER TABLE [dbo].[Link_LegacyMemberId_MVD_Ins] CHECK CONSTRAINT [FK_Link_MemberId_MVD_Ins_HPCustomer]