/****** Object:  Table [dbo].[LookupNPI_Used]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LookupNPI_Used](
	[NPI] [nvarchar](100) NOT NULL,
	[Entity Type Code] [nvarchar](1) NULL,
	[Provider Organization Name (Legal Business Name)] [nvarchar](100) NOT NULL,
	[Provider Last Name (Legal Name)] [nvarchar](100) NULL,
	[Provider First Name] [nvarchar](100) NULL,
	[Provider Credential Text] [nvarchar](20) NULL,
	[Provider First Line Business Practice Location Address] [nvarchar](100) NULL,
	[Provider Second Line Business Practice Location Address] [nvarchar](100) NULL,
	[Provider Business Practice Location Address City Name] [nvarchar](40) NULL,
	[Provider Business Practice Location Address State Name] [nvarchar](40) NULL,
	[Provider Business Practice Location Address Postal Code] [nvarchar](20) NULL,
	[Provider Business Practice Location Address Telephone Number] [nvarchar](20) NULL,
	[Provider Business Practice Location Address Fax Number] [nvarchar](20) NULL,
	[Other Provider Identifier_1] [nvarchar](20) NULL,
	[Other Provider Identifier State_1] [nvarchar](2) NULL,
	[Other Provider Identifier_2] [nvarchar](20) NULL,
	[Other Provider Identifier State_2] [nvarchar](2) NULL,
	[Other Provider Identifier_3] [nvarchar](20) NULL,
	[Other Provider Identifier State_3] [nvarchar](2) NULL,
	[Other Provider Identifier_4] [nvarchar](20) NULL,
	[Other Provider Identifier State_4] [nvarchar](2) NULL,
	[Other Provider Identifier_5] [nvarchar](20) NULL,
	[Other Provider Identifier State_5] [nvarchar](2) NULL,
	[Other Provider Identifier_6] [nvarchar](20) NULL,
	[Other Provider Identifier State_6] [nvarchar](2) NULL,
	[Other Provider Identifier_7] [nvarchar](20) NULL,
	[Other Provider Identifier State_7] [nvarchar](2) NULL,
	[Other Provider Identifier_8] [nvarchar](20) NULL,
	[Other Provider Identifier State_8] [nvarchar](2) NULL,
	[Other Provider Identifier_9] [nvarchar](20) NULL,
	[Other Provider Identifier State_9] [nvarchar](2) NULL,
	[Other Provider Identifier_10] [nvarchar](20) NULL,
	[Other Provider Identifier State_10] [nvarchar](2) NULL,
	[Other Provider Identifier_11] [nvarchar](20) NULL,
	[Other Provider Identifier State_11] [nvarchar](2) NULL,
	[Other Provider Identifier_12] [nvarchar](20) NULL,
	[Other Provider Identifier State_12] [nvarchar](2) NULL,
	[Other Provider Identifier_13] [nvarchar](20) NULL,
	[Other Provider Identifier State_13] [nvarchar](2) NULL,
	[Other Provider Identifier_14] [nvarchar](20) NULL,
	[Other Provider Identifier State_14] [nvarchar](2) NULL,
	[Other Provider Identifier_15] [nvarchar](20) NULL,
	[Other Provider Identifier State_15] [nvarchar](2) NULL,
	[Other Provider Identifier_16] [nvarchar](20) NULL,
	[Other Provider Identifier State_16] [nvarchar](2) NULL,
	[Other Provider Identifier_17] [nvarchar](20) NULL,
	[Other Provider Identifier State_17] [nvarchar](2) NULL,
	[Other Provider Identifier_18] [nvarchar](20) NULL,
	[Other Provider Identifier State_18] [nvarchar](2) NULL,
	[Other Provider Identifier_19] [nvarchar](20) NULL,
	[Other Provider Identifier State_19] [nvarchar](2) NULL,
	[Other Provider Identifier_20] [nvarchar](20) NULL,
	[Other Provider Identifier State_20] [nvarchar](2) NULL,
	[Other Provider Identifier_21] [nvarchar](20) NULL,
	[Other Provider Identifier State_21] [nvarchar](2) NULL,
	[Other Provider Identifier_22] [nvarchar](20) NULL,
	[Other Provider Identifier State_22] [nvarchar](2) NULL,
	[Other Provider Identifier_23] [nvarchar](20) NULL,
	[Other Provider Identifier State_23] [nvarchar](2) NULL,
	[Other Provider Identifier_24] [nvarchar](20) NULL,
	[Other Provider Identifier State_24] [nvarchar](2) NULL,
	[Other Provider Identifier_25] [nvarchar](20) NULL,
	[Other Provider Identifier State_25] [nvarchar](2) NULL,
	[Other Provider Identifier_26] [nvarchar](20) NULL,
	[Other Provider Identifier State_26] [nvarchar](2) NULL,
	[Other Provider Identifier_27] [nvarchar](20) NULL,
	[Other Provider Identifier State_27] [nvarchar](2) NULL,
	[Other Provider Identifier_28] [nvarchar](20) NULL,
	[Other Provider Identifier State_28] [nvarchar](20) NULL,
	[Other Provider Identifier_29] [nvarchar](20) NULL,
	[Other Provider Identifier State_29] [nvarchar](20) NULL,
	[Other Provider Identifier_30] [nvarchar](20) NULL,
	[Other Provider Identifier State_30] [nvarchar](2) NULL,
	[Other Provider Identifier_31] [nvarchar](20) NULL,
	[Other Provider Identifier State_31] [nvarchar](2) NULL,
	[Other Provider Identifier_32] [nvarchar](20) NULL,
	[Other Provider Identifier State_32] [nvarchar](2) NULL,
	[Other Provider Identifier_33] [nvarchar](20) NULL,
	[Other Provider Identifier State_33] [nvarchar](2) NULL,
	[Other Provider Identifier_34] [nvarchar](20) NULL,
	[Other Provider Identifier State_34] [nvarchar](2) NULL,
	[Other Provider Identifier_35] [nvarchar](20) NULL,
	[Other Provider Identifier State_35] [nvarchar](2) NULL,
	[Other Provider Identifier_36] [nvarchar](20) NULL,
	[Other Provider Identifier State_36] [nvarchar](2) NULL,
	[Other Provider Identifier_37] [nvarchar](20) NULL,
	[Other Provider Identifier State_37] [nvarchar](2) NULL,
	[Other Provider Identifier_38] [nvarchar](20) NULL,
	[Other Provider Identifier State_38] [nvarchar](2) NULL,
	[Other Provider Identifier_39] [nvarchar](20) NULL,
	[Other Provider Identifier State_39] [nvarchar](2) NULL,
	[Other Provider Identifier_40] [nvarchar](20) NULL,
	[Other Provider Identifier State_40] [nvarchar](2) NULL,
	[Other Provider Identifier_41] [nvarchar](20) NULL,
	[Other Provider Identifier State_41] [nvarchar](2) NULL,
	[Other Provider Identifier_42] [nvarchar](20) NULL,
	[Other Provider Identifier State_42] [nvarchar](2) NULL,
	[Other Provider Identifier_43] [nvarchar](20) NULL,
	[Other Provider Identifier State_43] [nvarchar](2) NULL,
	[Other Provider Identifier_44] [nvarchar](20) NULL,
	[Other Provider Identifier State_44] [nvarchar](2) NULL,
	[Other Provider Identifier_45] [nvarchar](20) NULL,
	[Other Provider Identifier State_45] [nvarchar](2) NULL,
	[Other Provider Identifier_46] [nvarchar](20) NULL,
	[Other Provider Identifier State_46] [nvarchar](2) NULL,
	[Other Provider Identifier_47] [nvarchar](20) NULL,
	[Other Provider Identifier State_47] [nvarchar](2) NULL,
	[Other Provider Identifier_48] [nvarchar](20) NULL,
	[Other Provider Identifier State_48] [nvarchar](2) NULL,
	[Other Provider Identifier_49] [nvarchar](20) NULL,
	[Other Provider Identifier State_49] [nvarchar](2) NULL,
	[Other Provider Identifier_50] [nvarchar](20) NULL,
	[Other Provider Identifier State_50] [nvarchar](2) NULL,
 CONSTRAINT [PK_Copy_LookupNPI_Used] PRIMARY KEY CLUSTERED 
(
	[NPI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]