/****** Object:  Table [dbo].[LookupNPI_Custom]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LookupNPI_Custom](
	[NPI] [nvarchar](10) NOT NULL,
	[Entity Type Code] [nvarchar](1) NULL,
	[Replacement NPI] [nvarchar](10) NULL,
	[Employer Identification Number (EIN)] [nvarchar](9) NULL,
	[Provider Organization Name (Legal Business Name)] [nvarchar](70) NULL,
	[Provider Last Name (Legal Name)] [nvarchar](35) NULL,
	[Provider First Name] [nvarchar](20) NULL,
	[Provider Middle Name] [nvarchar](20) NULL,
	[Provider Name Prefix Text] [nvarchar](5) NULL,
	[Provider Name Suffix Text] [nvarchar](5) NULL,
	[Provider Credential Text] [nvarchar](20) NULL,
	[Provider Other Organization Name] [nvarchar](70) NULL,
	[Provider Other Organization Name Type Code] [nvarchar](1) NULL,
	[Provider Other Last Name] [nvarchar](35) NULL,
	[Provider Other First Name] [nvarchar](20) NULL,
	[Provider Other Middle Name] [nvarchar](20) NULL,
	[Provider Other Name Prefix Text] [nvarchar](5) NULL,
	[Provider Other Name Suffix Text] [nvarchar](5) NULL,
	[Provider Other Credential Text] [nvarchar](20) NULL,
	[Provider Other Last Name Type Code] [nvarchar](1) NULL,
	[Provider First Line Business Mailing Address] [nvarchar](55) NULL,
	[Provider Second Line Business Mailing Address] [nvarchar](55) NULL,
	[Provider Business Mailing Address City Name] [nvarchar](40) NULL,
	[Provider Business Mailing Address State Name] [nvarchar](40) NULL,
	[Provider Business Mailing Address Postal Code] [nvarchar](20) NULL,
	[Provider Business Mailing Address Country Code (If outside U S )] [nvarchar](2) NULL,
	[Provider Business Mailing Address Telephone Number] [nvarchar](20) NULL,
	[Provider Business Mailing Address Fax Number] [nvarchar](20) NULL,
	[Provider First Line Business Practice Location Address] [nvarchar](55) NULL,
	[Provider Second Line Business Practice Location Address] [nvarchar](55) NULL,
	[Provider Business Practice Location Address City Name] [nvarchar](40) NULL,
	[Provider Business Practice Location Address State Name] [nvarchar](40) NULL,
	[Provider Business Practice Location Address Postal Code] [nvarchar](20) NULL,
	[Provider Business Practice Location Address Country Code (If outside U S )] [nvarchar](2) NULL,
	[Provider Business Practice Location Address Telephone Number] [nvarchar](20) NULL,
	[Provider Business Practice Location Address Fax Number] [nvarchar](20) NULL,
	[Provider Enumeration Date] [datetime] NULL,
	[Last Update Date] [nvarchar](40) NULL,
	[NPI Deactivation Reason Code] [nvarchar](2) NULL,
	[NPI Deactivation Date] [varchar](50) NULL,
	[NPI Reactivation Date] [varchar](50) NULL,
	[Provider Gender Code] [nvarchar](1) NULL,
	[Authorized Official Last Name] [nvarchar](35) NULL,
	[Authorized Official First Name] [nvarchar](20) NULL,
	[Authorized Official Middle Name] [nvarchar](20) NULL,
	[Authorized Official Title or Position] [nvarchar](35) NULL,
	[Authorized Official Telephone Number] [nvarchar](20) NULL,
	[Healthcare Provider Taxonomy Code_1] [nvarchar](10) NULL,
	[Provider License Number_1] [nvarchar](20) NULL,
	[Provider License Number State Code_1] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_1] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_2] [nvarchar](10) NULL,
	[Provider License Number_2] [nvarchar](20) NULL,
	[Provider License Number State Code_2] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_2] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_3] [nvarchar](10) NULL,
	[Provider License Number_3] [nvarchar](20) NULL,
	[Provider License Number State Code_3] [nvarchar](10) NULL,
	[Healthcare Provider Primary Taxonomy Switch_3] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_4] [nvarchar](10) NULL,
	[Provider License Number_4] [nvarchar](20) NULL,
	[Provider License Number State Code_4] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_4] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_5] [nvarchar](10) NULL,
	[Provider License Number_5] [nvarchar](20) NULL,
	[Provider License Number State Code_5] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_5] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_6] [nvarchar](10) NULL,
	[Provider License Number_6] [nvarchar](20) NULL,
	[Provider License Number State Code_6] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_6] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_7] [nvarchar](10) NULL,
	[Provider License Number_7] [nvarchar](20) NULL,
	[Provider License Number State Code_7] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_7] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_8] [nvarchar](10) NULL,
	[Provider License Number_8] [nvarchar](20) NULL,
	[Provider License Number State Code_8] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_8] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_9] [nvarchar](10) NULL,
	[Provider License Number_9] [nvarchar](20) NULL,
	[Provider License Number State Code_9] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_9] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_10] [nvarchar](10) NULL,
	[Provider License Number_10] [nvarchar](20) NULL,
	[Provider License Number State Code_10] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_10] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_11] [nvarchar](10) NULL,
	[Provider License Number_11] [nvarchar](20) NULL,
	[Provider License Number State Code_11] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_11] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_12] [nvarchar](10) NULL,
	[Provider License Number_12] [nvarchar](20) NULL,
	[Provider License Number State Code_12] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_12] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_13] [nvarchar](10) NULL,
	[Provider License Number_13] [nvarchar](20) NULL,
	[Provider License Number State Code_13] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_13] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_14] [nvarchar](10) NULL,
	[Provider License Number_14] [nvarchar](20) NULL,
	[Provider License Number State Code_14] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_14] [nvarchar](1) NULL,
	[Healthcare Provider Taxonomy Code_15] [nvarchar](10) NULL,
	[Provider License Number_15] [nvarchar](20) NULL,
	[Provider License Number State Code_15] [nvarchar](2) NULL,
	[Healthcare Provider Primary Taxonomy Switch_15] [nvarchar](1) NULL,
	[Other Provider Identifier_1] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_1] [nvarchar](2) NULL,
	[Other Provider Identifier State_1] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_1] [nvarchar](80) NULL,
	[Other Provider Identifier_2] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_2] [nvarchar](2) NULL,
	[Other Provider Identifier State_2] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_2] [nvarchar](80) NULL,
	[Other Provider Identifier_3] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_3] [nvarchar](2) NULL,
	[Other Provider Identifier State_3] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_3] [nvarchar](80) NULL,
	[Other Provider Identifier_4] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_4] [nvarchar](2) NULL,
	[Other Provider Identifier State_4] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_4] [nvarchar](80) NULL,
	[Other Provider Identifier_5] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_5] [nvarchar](2) NULL,
	[Other Provider Identifier State_5] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_5] [nvarchar](80) NULL,
	[Other Provider Identifier_6] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_6] [nvarchar](2) NULL,
	[Other Provider Identifier State_6] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_6] [nvarchar](80) NULL,
	[Other Provider Identifier_7] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_7] [nvarchar](2) NULL,
	[Other Provider Identifier State_7] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_7] [nvarchar](80) NULL,
	[Other Provider Identifier_8] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_8] [nvarchar](2) NULL,
	[Other Provider Identifier State_8] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_8] [nvarchar](80) NULL,
	[Other Provider Identifier_9] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_9] [nvarchar](2) NULL,
	[Other Provider Identifier State_9] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_9] [nvarchar](80) NULL,
	[Other Provider Identifier_10] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_10] [nvarchar](2) NULL,
	[Other Provider Identifier State_10] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_10] [nvarchar](80) NULL,
	[Other Provider Identifier_11] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_11] [nvarchar](2) NULL,
	[Other Provider Identifier State_11] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_11] [nvarchar](80) NULL,
	[Other Provider Identifier_12] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_12] [nvarchar](2) NULL,
	[Other Provider Identifier State_12] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_12] [nvarchar](80) NULL,
	[Other Provider Identifier_13] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_13] [nvarchar](2) NULL,
	[Other Provider Identifier State_13] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_13] [nvarchar](80) NULL,
	[Other Provider Identifier_14] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_14] [nvarchar](2) NULL,
	[Other Provider Identifier State_14] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_14] [nvarchar](80) NULL,
	[Other Provider Identifier_15] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_15] [nvarchar](2) NULL,
	[Other Provider Identifier State_15] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_15] [nvarchar](80) NULL,
	[Other Provider Identifier_16] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_16] [nvarchar](2) NULL,
	[Other Provider Identifier State_16] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_16] [nvarchar](80) NULL,
	[Other Provider Identifier_17] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_17] [nvarchar](2) NULL,
	[Other Provider Identifier State_17] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_17] [nvarchar](80) NULL,
	[Other Provider Identifier_18] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_18] [nvarchar](2) NULL,
	[Other Provider Identifier State_18] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_18] [nvarchar](80) NULL,
	[Other Provider Identifier_19] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_19] [nvarchar](2) NULL,
	[Other Provider Identifier State_19] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_19] [nvarchar](80) NULL,
	[Other Provider Identifier_20] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_20] [nvarchar](2) NULL,
	[Other Provider Identifier State_20] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_20] [nvarchar](80) NULL,
	[Other Provider Identifier_21] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_21] [nvarchar](2) NULL,
	[Other Provider Identifier State_21] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_21] [nvarchar](80) NULL,
	[Other Provider Identifier_22] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_22] [nvarchar](2) NULL,
	[Other Provider Identifier State_22] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_22] [nvarchar](80) NULL,
	[Other Provider Identifier_23] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_23] [nvarchar](2) NULL,
	[Other Provider Identifier State_23] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_23] [nvarchar](80) NULL,
	[Other Provider Identifier_24] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_24] [nvarchar](2) NULL,
	[Other Provider Identifier State_24] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_24] [nvarchar](80) NULL,
	[Other Provider Identifier_25] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_25] [nvarchar](2) NULL,
	[Other Provider Identifier State_25] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_25] [nvarchar](80) NULL,
	[Other Provider Identifier_26] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_26] [nvarchar](2) NULL,
	[Other Provider Identifier State_26] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_26] [nvarchar](80) NULL,
	[Other Provider Identifier_27] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_27] [nvarchar](2) NULL,
	[Other Provider Identifier State_27] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_27] [nvarchar](80) NULL,
	[Other Provider Identifier_28] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_28] [nvarchar](20) NULL,
	[Other Provider Identifier State_28] [nvarchar](20) NULL,
	[Other Provider Identifier Issuer_28] [nvarchar](80) NULL,
	[Other Provider Identifier_29] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_29] [nvarchar](2) NULL,
	[Other Provider Identifier State_29] [nvarchar](20) NULL,
	[Other Provider Identifier Issuer_29] [nvarchar](80) NULL,
	[Other Provider Identifier_30] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_30] [nvarchar](2) NULL,
	[Other Provider Identifier State_30] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_30] [nvarchar](80) NULL,
	[Other Provider Identifier_31] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_31] [nvarchar](2) NULL,
	[Other Provider Identifier State_31] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_31] [nvarchar](80) NULL,
	[Other Provider Identifier_32] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_32] [nvarchar](2) NULL,
	[Other Provider Identifier State_32] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_32] [nvarchar](80) NULL,
	[Other Provider Identifier_33] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_33] [nvarchar](2) NULL,
	[Other Provider Identifier State_33] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_33] [nvarchar](80) NULL,
	[Other Provider Identifier_34] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_34] [nvarchar](2) NULL,
	[Other Provider Identifier State_34] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_34] [nvarchar](80) NULL,
	[Other Provider Identifier_35] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_35] [nvarchar](2) NULL,
	[Other Provider Identifier State_35] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_35] [nvarchar](80) NULL,
	[Other Provider Identifier_36] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_36] [nvarchar](2) NULL,
	[Other Provider Identifier State_36] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_36] [nvarchar](80) NULL,
	[Other Provider Identifier_37] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_37] [nvarchar](2) NULL,
	[Other Provider Identifier State_37] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_37] [nvarchar](80) NULL,
	[Other Provider Identifier_38] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_38] [nvarchar](2) NULL,
	[Other Provider Identifier State_38] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_38] [nvarchar](80) NULL,
	[Other Provider Identifier_39] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_39] [nvarchar](2) NULL,
	[Other Provider Identifier State_39] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_39] [nvarchar](80) NULL,
	[Other Provider Identifier_40] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_40] [nvarchar](2) NULL,
	[Other Provider Identifier State_40] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_40] [nvarchar](80) NULL,
	[Other Provider Identifier_41] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_41] [nvarchar](2) NULL,
	[Other Provider Identifier State_41] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_41] [nvarchar](80) NULL,
	[Other Provider Identifier_42] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_42] [nvarchar](2) NULL,
	[Other Provider Identifier State_42] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_42] [nvarchar](80) NULL,
	[Other Provider Identifier_43] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_43] [nvarchar](2) NULL,
	[Other Provider Identifier State_43] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_43] [nvarchar](80) NULL,
	[Other Provider Identifier_44] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_44] [nvarchar](2) NULL,
	[Other Provider Identifier State_44] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_44] [nvarchar](80) NULL,
	[Other Provider Identifier_45] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_45] [nvarchar](2) NULL,
	[Other Provider Identifier State_45] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_45] [nvarchar](80) NULL,
	[Other Provider Identifier_46] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_46] [nvarchar](2) NULL,
	[Other Provider Identifier State_46] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_46] [nvarchar](80) NULL,
	[Other Provider Identifier_47] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_47] [nvarchar](2) NULL,
	[Other Provider Identifier State_47] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_47] [nvarchar](80) NULL,
	[Other Provider Identifier_48] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_48] [nvarchar](2) NULL,
	[Other Provider Identifier State_48] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_48] [nvarchar](80) NULL,
	[Other Provider Identifier_49] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_49] [nvarchar](2) NULL,
	[Other Provider Identifier State_49] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_49] [nvarchar](80) NULL,
	[Other Provider Identifier_50] [nvarchar](20) NULL,
	[Other Provider Identifier Type Code_50] [nvarchar](2) NULL,
	[Other Provider Identifier State_50] [nvarchar](2) NULL,
	[Other Provider Identifier Issuer_50] [nvarchar](80) NULL,
	[Is Sole Proprietor] [nvarchar](1) NULL,
	[Is Organization Subpart] [nvarchar](1) NULL,
	[Parent Organization LBN] [nvarchar](70) NULL,
	[Parent Organization TIN] [nvarchar](9) NULL,
	[Authorized Official Name Prefix Text] [nvarchar](5) NULL,
	[Authorized Official Name Suffix Text] [nvarchar](5) NULL,
	[Authorized Official Credential Text] [nvarchar](20) NULL,
	[MedicalGroup] [varchar](100) NULL,
	[OfficeHrMon] [varchar](50) NULL,
	[OfficeHrTue] [varchar](50) NULL,
	[OfficeHrWed] [varchar](50) NULL,
	[OfficeHrThu] [varchar](50) NULL,
	[OfficeHrFri] [varchar](50) NULL,
	[OfficeHrSat] [varchar](50) NULL,
	[OfficeHrSun] [varchar](50) NULL,
	[Note] [varchar](4000) NULL,
	[Specialty] [varchar](100) NULL,
	[HospAffiliations] [varchar](1000) NULL,
	[Certification] [varchar](1000) NULL,
 CONSTRAINT [PK_LookupNPI_Custom] PRIMARY KEY CLUSTERED 
(
	[NPI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]