/****** Object:  Table [dbo].[LookupImmunizationCPT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LookupImmunizationCPT](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CPTCode] [varchar](5) NULL,
	[ImmunName] [varchar](50) NULL,
 CONSTRAINT [PK_LookupImmunizationCPT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_LookupImmunizationCPT_CPTCode] ON [dbo].[LookupImmunizationCPT]
(
	[CPTCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]