/****** Object:  Table [dbo].[LookupLOINC]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LookupLOINC](
	[LOINC_NUM] [varchar](20) NOT NULL,
	[Component] [varchar](1000) NULL,
	[Property] [varchar](50) NULL,
	[Time_Aspct] [varchar](50) NULL,
	[System] [varchar](1000) NULL,
	[Scale_Typ] [varchar](50) NULL,
	[Method_Typ] [varchar](50) NULL,
	[Relat_nms] [varchar](1000) NULL,
	[Class] [varchar](50) NULL,
	[Source] [varchar](50) NULL,
	[DT_Last_Ch] [varchar](50) NULL,
	[Chng_Type] [varchar](50) NULL,
	[Comments] [varchar](max) NULL,
	[AnswerList] [varchar](1000) NULL,
	[Status] [varchar](50) NULL,
	[Map_To] [varchar](50) NULL,
	[Scope] [varchar](50) NULL,
	[Consumer_Name] [varchar](1000) NULL,
	[Ipcc_Units] [varchar](50) NULL,
	[Reference] [varchar](1000) NULL,
	[Exact_cmp_sy] [varchar](50) NULL,
	[Molar_Mass] [varchar](50) NULL,
	[ClassType] [varchar](50) NULL,
	[Formula] [varchar](1000) NULL,
	[Species] [varchar](50) NULL,
	[Exmpl_Answers] [varchar](4000) NULL,
	[Acssym] [varchar](4000) NULL,
	[Base_Name] [varchar](50) NULL,
	[Final] [varchar](50) NULL,
	[Naaccr_ID] [varchar](50) NULL,
	[Code_Table] [varchar](50) NULL,
	[SetRoot] [varchar](50) NULL,
	[PanelElements] [varchar](1000) NULL,
	[Survey_Quest_Text] [varchar](1000) NULL,
	[Survey_Quest_src] [varchar](50) NULL,
	[UnitsRequired] [varchar](50) NULL,
	[Submitted_Units] [varchar](50) NULL,
	[RelatedNames2] [varchar](1000) NULL,
	[ShortName] [varchar](50) NULL,
	[Order_Obs] [varchar](50) NULL,
	[Cdisc_Common_Tests] [varchar](50) NULL,
	[HL7_Field_Subfield_ID] [varchar](50) NULL,
	[External_Copyright_Notice] [varchar](4000) NULL,
	[Example_Units] [varchar](1000) NULL,
	[Inpc_Percentage] [varchar](50) NULL,
	[Long_Common_Name] [varchar](1000) NULL,
	[HL7_V2_DataType] [varchar](50) NULL,
	[HL7_V3_DataType] [varchar](50) NULL,
	[Curated_Range_And_Units] [varchar](50) NULL,
	[Document_Section] [varchar](50) NULL,
	[Definition_Description_Help] [varchar](4000) NULL,
	[Example_Ucum_Units] [varchar](50) NULL,
 CONSTRAINT [PK_LookupLOINC] PRIMARY KEY CLUSTERED 
(
	[LOINC_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]