/****** Object:  Table [dbo].[LookupICD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LookupICD](
	[Code] [varchar](10) NOT NULL,
	[ChangeIndicator] [nvarchar](1) NULL,
	[Status] [nvarchar](1) NULL,
	[ShortDesc] [varchar](48) NULL,
	[MediumDesc] [varchar](60) NULL,
	[LongDesc] [varchar](500) NULL,
	[LongDescCont] [nchar](219) NULL,
	[Type] [nchar](50) NOT NULL,
	[CodeNoPeriod] [varchar](10) NULL,
	[ICDNo] [varchar](10) NOT NULL,
	[ParentCode] [varchar](10) NULL,
	[ParentCodeNoPeriod] [varchar](10) NULL,
	[MonthID] [int] NULL,
 CONSTRAINT [PK_LookupICD] PRIMARY KEY CLUSTERED 
(
	[Code] ASC,
	[ICDNo] ASC,
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE UNIQUE NONCLUSTERED INDEX [IX_LookupICD] ON [dbo].[LookupICD]
(
	[CodeNoPeriod] ASC,
	[ICDNo] ASC,
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_NCI_LookupICD_Hier_CodeNoPeriods] ON [dbo].[LookupICD]
(
	[CodeNoPeriod] ASC,
	[ParentCodeNoPeriod] ASC,
	[ICDNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_NCI_LookupICD_Hier_Codes] ON [dbo].[LookupICD]
(
	[Code] ASC,
	[ICDNo] ASC,
	[ParentCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_NCI_LookupICD_ICDNo] ON [dbo].[LookupICD]
(
	[ICDNo] ASC
)
INCLUDE([MediumDesc],[CodeNoPeriod]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]