/****** Object:  Table [dbo].[MainToDoHEDIS_Expired]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainToDoHEDIS_Expired](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MemberID] [varchar](20) NOT NULL,
	[Major] [nvarchar](300) NOT NULL,
	[Minor] [nvarchar](100) NOT NULL,
	[Source] [varchar](50) NULL,
	[Created] [datetime] NULL,
	[TestLookupID] [int] NULL,
	[ExpiredDate] [datetime] NULL,
	[MVDID] [varchar](20) NULL,
	[DOB] [datetime] NULL,
	[EpisodeDate] [datetime] NULL,
 CONSTRAINT [PK_MainToDoHEDIS_Expired] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Expired_LookupID] ON [dbo].[MainToDoHEDIS_Expired]
(
	[TestLookupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Expired_LookupID_Source] ON [dbo].[MainToDoHEDIS_Expired]
(
	[TestLookupID] ASC,
	[Source] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Expired_MVDID] ON [dbo].[MainToDoHEDIS_Expired]
(
	[MVDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
ALTER TABLE [dbo].[MainToDoHEDIS_Expired] ADD  CONSTRAINT [DF__MainToDoH__Expir__31E316DC]  DEFAULT (getutcdate()) FOR [ExpiredDate]