/****** Object:  Table [dbo].[MainToDoHEDISStaging]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainToDoHEDISStaging](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MemberID] [varchar](20) NOT NULL,
	[Major] [nvarchar](100) NOT NULL,
	[Minor] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_MainToDoHEDISStaging] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDISStaging] ON [dbo].[MainToDoHEDISStaging]
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]