/****** Object:  Table [dbo].[MainToDoHEDIS_RemindIn_NEW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainToDoHEDIS_RemindIn_NEW](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DaysCount] [int] NULL,
	[MVDID] [varchar](20) NULL,
	[TestID] [int] NULL,
	[Created] [datetime] NULL,
	[CreatedBy] [varchar](50) NULL,
 CONSTRAINT [PK_MainToDoHEDIS_RemindIn] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_RemindIn] ON [dbo].[MainToDoHEDIS_RemindIn_NEW]
(
	[MVDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_RemindIn_NEW] ON [dbo].[MainToDoHEDIS_RemindIn_NEW]
(
	[MVDID] ASC,
	[TestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[MainToDoHEDIS_RemindIn_NEW] ADD  CONSTRAINT [DF_MainToDoHEDIS_RemindIn_Created]  DEFAULT (getutcdate()) FOR [Created]