/****** Object:  Table [dbo].[MainICENUMBERGroups]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainICENUMBERGroups](
	[ICENUMBER] [varchar](15) NOT NULL,
	[ICEGROUP] [varchar](15) NULL,
	[MainAccount] [bit] NULL,
	[SecondaryICENUMBER] [varchar](15) NULL,
	[HVUserID] [char](36) NULL,
	[HVRecordID] [char](36) NULL,
	[CreationDate] [datetime] NULL,
	[ModifyDate] [datetime] NULL,
 CONSTRAINT [PK_MainICENUMBERGroups] PRIMARY KEY CLUSTERED 
(
	[ICENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainICENUMBERGroups] ON [dbo].[MainICENUMBERGroups]
(
	[ICEGROUP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]