/****** Object:  Table [dbo].[MainToDoHEDIS_Summary]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainToDoHEDIS_Summary](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NPI] [varchar](50) NULL,
	[TestDueID] [int] NULL,
	[TotalPatients] [int] NULL,
	[TestDuePatientCount] [int] NULL,
	[Created] [datetime] NULL,
	[TestCompletedPatientCount] [int] NULL,
	[CustID] [int] NULL,
	[TIN] [varchar](20) NULL,
 CONSTRAINT [PK_MainToDoHEDIS_Summary] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Summary_NPI] ON [dbo].[MainToDoHEDIS_Summary]
(
	[NPI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Summary_TestID] ON [dbo].[MainToDoHEDIS_Summary]
(
	[TestDueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_Summary_TIN] ON [dbo].[MainToDoHEDIS_Summary]
(
	[TIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
ALTER TABLE [dbo].[MainToDoHEDIS_Summary] ADD  CONSTRAINT [DF_MainToDoHEDIS_Summary_Created]  DEFAULT (getdate()) FOR [Created]