/****** Object:  Table [dbo].[MainToDoHEDIS_NEW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MainToDoHEDIS_NEW](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MemberID] [varchar](20) NOT NULL,
	[Major] [nvarchar](300) NOT NULL,
	[Minor] [nvarchar](100) NOT NULL,
	[Source] [varchar](50) NULL,
	[Created] [datetime] NULL,
	[TestLookupID] [int] NULL,
	[MVDID] [varchar](20) NULL,
	[StatusID] [int] NULL,
	[EpisodeDate] [datetime] NULL,
	[DOB] [date] NULL,
	[VisitCount] [int] NULL,
	[LastVisit] [datetime] NULL,
	[StatusIDSaveDate] [datetime] NULL,
	[StatusUpdatedBy] [varchar](50) NULL,
 CONSTRAINT [PK_MainToDoHEDIS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_MemberID] ON [dbo].[MainToDoHEDIS_NEW]
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_mvdid] ON [dbo].[MainToDoHEDIS_NEW]
(
	[MVDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MainToDoHEDIS_NEW] ON [dbo].[MainToDoHEDIS_NEW]
(
	[MVDID] ASC,
	[TestLookupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[MainToDoHEDIS_NEW] ADD  CONSTRAINT [DF__MainToDoH__Creat__73E5E463]  DEFAULT (getutcdate()) FOR [Created]
ALTER TABLE [dbo].[MainToDoHEDIS_NEW]  WITH CHECK ADD  CONSTRAINT [FK_MainToDoHEDIS_LookupTestDueStatus] FOREIGN KEY([StatusID])
REFERENCES [dbo].[LookupTestDueStatus] ([ID])
ALTER TABLE [dbo].[MainToDoHEDIS_NEW] CHECK CONSTRAINT [FK_MainToDoHEDIS_LookupTestDueStatus]