/****** Object:  Table [dbo].[NDC_NEW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[NDC_NEW](
	[PRODUCTID] [varchar](500) NULL,
	[PRODUCTNDC] [varchar](500) NULL,
	[PRODUCTTYPENAME] [varchar](500) NULL,
	[PROPRIETARYNAME] [varchar](4000) NULL,
	[PROPRIETARYNAMESUFFIX] [varchar](4000) NULL,
	[NONPROPRIETARYNAME] [varchar](4000) NULL,
	[DOSAGEFORMNAME] [varchar](4000) NULL,
	[ROUTENAME] [varchar](4000) NULL,
	[STARTMARKETINGDATE] [varchar](4000) NULL,
	[ENDMARKETINGDATE] [varchar](4000) NULL,
	[MARKETINGCATEGORYNAME] [varchar](4000) NULL,
	[APPLICATIONNUMBER] [varchar](4000) NULL,
	[LABELERNAME] [varchar](4000) NULL,
	[SUBSTANCENAME] [varchar](4000) NULL,
	[ACTIVE_NUMERATOR_STRENGTH] [varchar](4000) NULL,
	[ACTIVE_INGRED_UNIT] [varchar](4000) NULL,
	[PHARM_CLASSES] [varchar](4000) NULL,
	[DEASCHEDULE] [varchar](4000) NULL
) ON [PRIMARY]