/****** Object:  Table [dbo].[PCPTaxonomy]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PCPTaxonomy](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TaxonomyCode] [varchar](50) NULL,
 CONSTRAINT [PK_PCPTaxonomy] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]