/****** Object:  Table [dbo].[tags_for_high_risk_PTB_members]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[tags_for_high_risk_PTB_members](
	[PartyKey] [varchar](255) NULL,
	[MemberID] [varchar](15) NULL,
	[MVDID] [varchar](30) NULL,
	[LOB] [varchar](2) NULL,
	[CmOrgRegion] [varchar](50) NULL,
	[PredictionDate] [varchar](255) NULL,
	[ConceptionDate] [varchar](255) NULL,
	[Count_Days_post_Conception] [int] NULL,
	[Is_Top10pct_predicted] [int] NOT NULL,
	[Is_recurring] [int] NOT NULL,
	[Top_k_pct_predicted] [bigint] NULL,
	[Is_SUD3_predicted] [int] NOT NULL,
	[Is_Ortho3_predicted] [int] NOT NULL,
	[Is_Renal3_predicted] [int] NOT NULL,
	[Is_Depress3_predicted] [int] NOT NULL,
	[Med_PaidAmt_Prev360d] [decimal](38, 2) NOT NULL,
	[RX_PaidAmt_Prev360d] [decimal](38, 2) NOT NULL,
	[SDOH_Vulnerable_OverAll] [decimal](18, 2) NULL,
	[SDOH_Vulnerable_Socioeconomic] [decimal](18, 2) NULL,
	[SDOH_Vulnerable_HH_ComposiitonDisability] [decimal](18, 2) NULL,
	[SDOH_Vulnerable_Language] [decimal](18, 2) NULL,
	[SDOH_Vulnerable_Transportation] [decimal](18, 2) NULL,
	[Avg_MME_per_DayOnMME_Prev360d] [decimal](18, 2) NULL,
	[Max_MME_per_DayOnMME_Prev360d] [decimal](18, 2) NULL,
	[Total_MME_Prev360d] [decimal](18, 2) NULL,
	[Family_Size] [int] NULL,
	[Has_Depressed_Family_Members_in_History] [int] NULL,
	[Is_Depressed_in_History] [int] NULL,
	[Has_Obesity_History] [int] NOT NULL,
	[Latest_Obesity_Dx_in_History] [date] NULL,
	[Latest_Rx_Fill] [date] NULL,
	[Latest_Visit_to_Provider] [date] NULL,
	[Has_Visit_to_Provider_in_Prev120d] [int] NOT NULL,
	[Latest_Visit_to_ED] [date] NULL,
	[Count_EDvisits_in_Prev120d] [int] NOT NULL,
	[GapInCare_CDC_ha1c] [int] NULL,
	[GapInCare_mammogram] [int] NULL,
	[GapInCare_MedExam] [int] NULL,
	[Has_DiabetesMellitus_past720d] [int] NULL,
	[Count_Dist_Chronic_ICD10dx_in_history] [int] NOT NULL,
	[Count_Dist_Chronic_CCS_in_history] [int] NOT NULL,
	[Count_Dist_Chronic_BodySystem_in_history] [int] NOT NULL,
	[ElixGrp_AA_in_history] [int] NOT NULL,
	[ElixGrp_BLA_in_history] [int] NOT NULL,
	[ElixGrp_CA_in_history] [int] NOT NULL,
	[ElixGrp_CHF_in_history] [int] NOT NULL,
	[ElixGrp_Coag_in_history] [int] NOT NULL,
	[ElixGrp_COPD_in_history] [int] NOT NULL,
	[ElixGrp_DA_in_history] [int] NOT NULL,
	[ElixGrp_DC_in_history] [int] NOT NULL,
	[ElixGrp_Depres_in_history] [int] NOT NULL,
	[ElixGrp_DrgAbuse_in_history] [int] NOT NULL,
	[ElixGrp_DUC_in_history] [int] NOT NULL,
	[ElixGrp_FED_in_history] [int] NOT NULL,
	[ElixGrp_HC_in_history] [int] NOT NULL,
	[ElixGrp_HIV_in_history] [int] NOT NULL,
	[ElixGrp_HUC_in_history] [int] NOT NULL,
	[ElixGrp_Hy_in_history] [int] NOT NULL,
	[ElixGrp_LD_in_history] [int] NOT NULL,
	[ElixGrp_Ly_in_history] [int] NOT NULL,
	[ElixGrp_MC_in_history] [int] NOT NULL,
	[ElixGrp_OBS_in_history] [int] NOT NULL,
	[ElixGrp_OND_in_history] [int] NOT NULL,
	[ElixGrp_Paralysis_in_history] [int] NOT NULL,
	[ElixGrp_PCD_in_history] [int] NOT NULL,
	[ElixGrp_Psycs_in_history] [int] NOT NULL,
	[ElixGrp_PUDExB_in_history] [int] NOT NULL,
	[ElixGrp_PVD_in_history] [int] NOT NULL,
	[ElixGrp_RA_in_history] [int] NOT NULL,
	[ElixGrp_RF_in_history] [int] NOT NULL,
	[ElixGrp_STM_in_history] [int] NOT NULL,
	[ElixGrp_VD_in_history] [int] NOT NULL,
	[ElixGrp_WgtLoss_in_history] [int] NOT NULL,
	[Has_Chronic_SUD_in_history] [int] NULL,
	[Model_Used] [varchar](8) NOT NULL
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_PartyKey] ON [dbo].[tags_for_high_risk_PTB_members]
(
	[PartyKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]