/****** Object:  Table [dbo].[temp_sunny_PBI]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[temp_sunny_PBI](
	[MemberID] [varchar](15) NULL,
	[Zipcode] [varchar](9) NULL,
	[SubscriberID] [varchar](10) NULL,
	[CmOrgRegion] [varchar](50) NULL,
	[Relationship] [varchar](2) NULL,
	[MVDID] [varchar](30) NOT NULL,
	[ClaimNumber] [varchar](20) NULL,
	[StatementFromDate] [date] NULL,
	[Code] [varchar](12) NULL,
	[TypeOfDiag] [varchar](5) NOT NULL,
	[RiskGroupID] [int] NULL,
	[MemberFirstName] [varchar](50) NULL,
	[MemberLastName] [varchar](50) NULL,
	[Age] [int] NULL,
	[Sex] [varchar](1) NULL,
	[EmergencyIndicator] [bit] NULL,
	[NetworkIndicator] [varchar](1) NULL,
	[AdmissionDate] [datetime] NULL,
	[DischargeDate] [datetime] NULL,
	[DischargeStatusCode] [varchar](2) NULL,
	[BilledAmount] [decimal](18, 2) NULL,
	[ClaimStatus] [varchar](5) NULL,
	[FacilityTIN] [varchar](10) NULL,
	[PartyKey] [int] NULL,
	[CaseId] [varchar](1000) NULL,
	[CaseOwner] [varchar](500) NULL,
	[CaseProgram] [varchar](200) NULL,
	[FormDate] [datetime] NULL,
	[FormAuthor] [varchar](100) NULL,
	[EngagementType] [varchar](max) NULL,
	[WhoContacted] [varchar](max) NULL,
	[Disposition] [varchar](max) NULL,
	[Col1] [varchar](1) NOT NULL,
	[Col2] [varchar](1) NOT NULL,
	[Col3] [varchar](1) NOT NULL,
	[Col4] [varchar](1) NOT NULL,
	[Col5] [varchar](1) NOT NULL,
	[Col6] [varchar](1) NOT NULL,
	[Col7] [varchar](1) NOT NULL,
	[Col8] [varchar](1) NOT NULL,
	[Col9] [varchar](1) NOT NULL,
	[Col10] [varchar](1) NOT NULL,
	[Col11] [varchar](1) NOT NULL,
	[Col12] [varchar](1) NOT NULL,
	[Col13] [varchar](1) NOT NULL,
	[Col14] [varchar](1) NOT NULL,
	[Col15] [varchar](1) NOT NULL,
	[Col16] [varchar](1) NOT NULL,
	[Col17] [varchar](1) NOT NULL,
	[Col18] [varchar](1) NOT NULL,
	[Col19] [varchar](1) NOT NULL,
	[Col20] [varchar](1) NOT NULL,
	[Col21] [varchar](1) NOT NULL,
	[Col22] [varchar](1) NOT NULL,
	[Col23] [varchar](1) NOT NULL,
	[Col24] [varchar](1) NOT NULL,
	[Col25] [varchar](1) NOT NULL,
	[Col26] [varchar](1) NOT NULL,
	[Col27] [varchar](1) NOT NULL,
	[Col28] [varchar](1) NOT NULL,
	[Col29] [varchar](1) NOT NULL,
	[Col30] [varchar](1) NOT NULL,
	[Col31] [varchar](1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]