/****** Object:  Table [Rules].[MainPersonalStats]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [Rules].[MainPersonalStats](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Cust_ID] [int] NULL,
	[MVDID] [varchar](50) NULL,
	[MemberID] [varchar](50) NULL,
	[MonthID] [varchar](6) NULL,
	[PCP_TIN] [varchar](50) NULL,
	[PCP_NPI] [varchar](50) NULL,
	[LOB] [varchar](20) NULL,
	[IsW15] [bit] NULL,
	[IsW15_Mod1] [bit] NULL,
	[IsW34] [bit] NULL,
	[IsAWC] [bit] NULL,
	[IsLSC] [bit] NULL,
	[IsBCS] [bit] NULL,
	[IsCCS] [bit] NULL,
	[IsCOL] [bit] NULL,
	[IsCAP] [bit] NULL,
	[IsASM] [bit] NULL,
	[IsCIS] [bit] NULL,
	[IsCWP] [bit] NULL,
	[IsAMR] [bit] NULL,
	[IsAMR_Mod1] [bit] NULL,
	[IsFUH7] [bit] NULL,
	[IsFUH30] [bit] NULL,
	[IsURI] [bit] NULL,
	[IsADD_Init] [bit] NULL,
	[IsADD_CM] [bit] NULL,
	[IsPPC1] [bit] NULL,
	[IsPPC2] [bit] NULL,
	[IsCISCMB2] [bit] NULL,
	[IsCISCMB3] [bit] NULL,
	[IsCISCMB4] [bit] NULL,
	[IsCISCMB5] [bit] NULL,
	[IsCISCMB6] [bit] NULL,
	[IsCISCMB7] [bit] NULL,
	[IsCISCMB8] [bit] NULL,
	[IsCISCMB9] [bit] NULL,
	[IsCISCMB10] [bit] NULL,
	[IsCISDTP] [bit] NULL,
	[IsCISHEPA] [bit] NULL,
	[IsCISHEPB] [bit] NULL,
	[IsCISHIB] [bit] NULL,
	[IsCISINFL] [bit] NULL,
	[IsCISMMR] [bit] NULL,
	[IsCISIPV] [bit] NULL,
	[IsCISPNEU] [bit] NULL,
	[IsCISROTA] [bit] NULL,
	[IsCISVZV] [bit] NULL,
	[IsCDC1] [bit] NULL,
	[IsCDC2] [bit] NULL,
	[IsCDC3] [bit] NULL,
	[IsCDC4] [bit] NULL,
	[IsCDC7] [bit] NULL,
	[IsCDC9] [bit] NULL,
	[IsCDC10] [bit] NULL,
	[IsWCC1] [bit] NULL,
	[IsWCC2] [bit] NULL,
	[IsWCC3] [bit] NULL,
	[IsCBP] [bit] NULL,
	[IsMMA1A] [bit] NULL,
	[IsMMA1B] [bit] NULL,
	[IsMMA2A] [bit] NULL,
	[IsMMA2B] [bit] NULL,
	[IsMMA3A] [bit] NULL,
	[IsMMA3B] [bit] NULL,
	[IsMMA4A] [bit] NULL,
	[IsMMA4B] [bit] NULL,
	[IsIMAMEN] [bit] NULL,
	[IsIMATD] [bit] NULL,
	[IsIMAHPV] [bit] NULL,
	[IsABA] [bit] NULL,
	[IsAAB] [bit] NULL,
	[IsAMM1] [bit] NULL,
	[IsAMM2] [bit] NULL,
	[IsNCS] [bit] NULL,
	[IsASM1] [bit] NULL,
	[IsASM2] [bit] NULL,
	[IsASM3] [bit] NULL,
	[IsASM4] [bit] NULL,
	[IsIMACMB1] [bit] NULL,
	[IsIMACMB2] [bit] NULL,
	[LastDrugDispensedDate] [date] NULL,
	[LastERVisit] [date] NULL,
	[LastLABVisit] [date] NULL,
	[LastPhysicianVisit] [date] NULL,
	[Rolling12MonthERVisits] [smallint] NULL,
	[Rolling12MonthLABVisits] [smallint] NULL,
	[Rolling12MonthPhysicianVisits] [smallint] NULL,
	[Rolling12MonthAcuteVisits] [smallint] NULL,
	[Rolling12MonthBHVisits] [smallint] NULL,
	[Rolling12MonthNFVisits] [smallint] NULL,
	[Rolling12MonthRehabVisits] [smallint] NULL,
	[Rolling12MonthAllClaimCost] [money] NULL,
	[Rolling12MonthRxClaimCost] [money] NULL,
	[YTDAllClaimCost] [money] NULL,
	[YTDRxClaimCost] [money] NULL,
	[CreationDate] [datetime] NULL,
	[ModifyDate] [datetime] NULL,
	[Preg_Cond] [bit] NULL,
	[HouseholdSize] [int] NULL,
	[ClaimCount] [int] NULL,
	[ClaimLineCount] [int] NULL,
	[Charlson_Cat_MI] [bit] NULL,
	[Charlson_Cat_CHF] [bit] NULL,
	[Charlson_Cat_PVD] [bit] NULL,
	[Charlson_Cat_CVA] [bit] NULL,
	[Charlson_Cat_DEMENTIA] [bit] NULL,
	[Charlson_Cat_COPD] [bit] NULL,
	[Charlson_Cat_RHEUMATIC] [bit] NULL,
	[Charlson_Cat_ULCER] [bit] NULL,
	[Charlson_Cat_MILDLIVER] [bit] NULL,
	[Charlson_Cat_DM] [bit] NULL,
	[Charlson_Cat_DMENDORGAN] [bit] NULL,
	[Charlson_Cat_PLEGIA] [bit] NULL,
	[Charlson_Cat_RENAL] [bit] NULL,
	[Charlson_Cat_CANCER] [bit] NULL,
	[Charlson_Cat_SEVERELIVER] [bit] NULL,
	[Charlson_Cat_METASTASES] [bit] NULL,
	[Charlson_Cat_HIV] [bit] NULL,
	[Elix_Grp_CHF] [bit] NULL,
	[Elix_Grp_CA] [bit] NULL,
	[Elix_Grp_VD] [bit] NULL,
	[Elix_Grp_PCD] [bit] NULL,
	[Elix_Grp_PVD] [bit] NULL,
	[Elix_Grp_HUC] [bit] NULL,
	[Elix_Grp_HC] [bit] NULL,
	[Elix_Grp_Paralysis] [bit] NULL,
	[Elix_Grp_OND] [bit] NULL,
	[Elix_Grp_COPD] [bit] NULL,
	[Elix_Grp_DUC] [bit] NULL,
	[Elix_Grp_DC] [bit] NULL,
	[Elix_Grp_Hy] [bit] NULL,
	[Elix_Grp_RF] [bit] NULL,
	[Elix_Grp_LD] [bit] NULL,
	[Elix_Grp_PUDExB] [bit] NULL,
	[Elix_Grp_HIV] [bit] NULL,
	[Elix_Grp_Ly] [bit] NULL,
	[Elix_Grp_MC] [bit] NULL,
	[Elix_Grp_STM] [bit] NULL,
	[Elix_Grp_RA] [bit] NULL,
	[Elix_Grp_Coag] [bit] NULL,
	[Elix_Grp_OBS] [bit] NULL,
	[Elix_Grp_WgtLoss] [bit] NULL,
	[Elix_Grp_FED] [bit] NULL,
	[Elix_Grp_BLA] [bit] NULL,
	[Elix_Grp_DA] [bit] NULL,
	[Elix_Grp_AA] [bit] NULL,
	[Elix_Grp_DrgAbuse] [bit] NULL,
	[Elix_Grp_Psycs] [bit] NULL,
	[Elix_Grp_Depres] [bit] NULL,
	[HCC000] [bit] NULL,
	[HCC001] [bit] NULL,
	[HCC002] [bit] NULL,
	[HCC003] [bit] NULL,
	[HCC004] [bit] NULL,
	[HCC006] [bit] NULL,
	[HCC008] [bit] NULL,
	[HCC009] [bit] NULL,
	[HCC010] [bit] NULL,
	[HCC011] [bit] NULL,
	[HCC012] [bit] NULL,
	[HCC013] [bit] NULL,
	[HCC018] [bit] NULL,
	[HCC019] [bit] NULL,
	[HCC020] [bit] NULL,
	[HCC021] [bit] NULL,
	[HCC023] [bit] NULL,
	[HCC026] [bit] NULL,
	[HCC027] [bit] NULL,
	[HCC028] [bit] NULL,
	[HCC029] [bit] NULL,
	[HCC030] [bit] NULL,
	[HCC034] [bit] NULL,
	[HCC035] [bit] NULL,
	[HCC036] [bit] NULL,
	[HCC037] [bit] NULL,
	[HCC038] [bit] NULL,
	[HCC041] [bit] NULL,
	[HCC042] [bit] NULL,
	[HCC045] [bit] NULL,
	[HCC046] [bit] NULL,
	[HCC047] [bit] NULL,
	[HCC048] [bit] NULL,
	[HCC054] [bit] NULL,
	[HCC055] [bit] NULL,
	[HCC056] [bit] NULL,
	[HCC057] [bit] NULL,
	[HCC061] [bit] NULL,
	[HCC062] [bit] NULL,
	[HCC063] [bit] NULL,
	[HCC064] [bit] NULL,
	[HCC066] [bit] NULL,
	[HCC067] [bit] NULL,
	[HCC068] [bit] NULL,
	[HCC069] [bit] NULL,
	[HCC070] [bit] NULL,
	[HCC071] [bit] NULL,
	[HCC073] [bit] NULL,
	[HCC074] [bit] NULL,
	[HCC075] [bit] NULL,
	[HCC081] [bit] NULL,
	[HCC082] [bit] NULL,
	[HCC087] [bit] NULL,
	[HCC088] [bit] NULL,
	[HCC089] [bit] NULL,
	[HCC090] [bit] NULL,
	[HCC094] [bit] NULL,
	[HCC096] [bit] NULL,
	[HCC097] [bit] NULL,
	[HCC102] [bit] NULL,
	[HCC103] [bit] NULL,
	[HCC106] [bit] NULL,
	[HCC107] [bit] NULL,
	[HCC108] [bit] NULL,
	[HCC109] [bit] NULL,
	[HCC110] [bit] NULL,
	[HCC111] [bit] NULL,
	[HCC112] [bit] NULL,
	[HCC113] [bit] NULL,
	[HCC114] [bit] NULL,
	[HCC115] [bit] NULL,
	[HCC117] [bit] NULL,
	[HCC118] [bit] NULL,
	[HCC119] [bit] NULL,
	[HCC120] [bit] NULL,
	[HCC121] [bit] NULL,
	[HCC122] [bit] NULL,
	[HCC125] [bit] NULL,
	[HCC126] [bit] NULL,
	[HCC127] [bit] NULL,
	[HCC128] [bit] NULL,
	[HCC129] [bit] NULL,
	[HCC130] [bit] NULL,
	[HCC131] [bit] NULL,
	[HCC132] [bit] NULL,
	[HCC135] [bit] NULL,
	[HCC137] [bit] NULL,
	[HCC138] [bit] NULL,
	[HCC139] [bit] NULL,
	[HCC142] [bit] NULL,
	[HCC145] [bit] NULL,
	[HCC146] [bit] NULL,
	[HCC149] [bit] NULL,
	[HCC150] [bit] NULL,
	[HCC151] [bit] NULL,
	[HCC153] [bit] NULL,
	[HCC154] [bit] NULL,
	[HCC156] [bit] NULL,
	[HCC158] [bit] NULL,
	[HCC159] [bit] NULL,
	[HCC160] [bit] NULL,
	[HCC161] [bit] NULL,
	[HCC162] [bit] NULL,
	[HCC163] [bit] NULL,
	[HCC183] [bit] NULL,
	[HCC184] [bit] NULL,
	[HCC187] [bit] NULL,
	[HCC188] [bit] NULL,
	[HCC203] [bit] NULL,
	[HCC204] [bit] NULL,
	[HCC205] [bit] NULL,
	[HCC207] [bit] NULL,
	[HCC208] [bit] NULL,
	[HCC209] [bit] NULL,
	[HCC217] [bit] NULL,
	[HCC226] [bit] NULL,
	[HCC227] [bit] NULL,
	[HCC243] [bit] NULL,
	[HCC245] [bit] NULL,
	[HCC246] [bit] NULL,
	[HCC247] [bit] NULL,
	[HCC248] [bit] NULL,
	[HCC249] [bit] NULL,
	[HCC251] [bit] NULL,
	[HCC253] [bit] NULL,
	[HCC254] [bit] NULL,
	[Annual_Exam_30] [bit] NULL,
	[Annual_Exam_50] [bit] NULL,
	[Annual_Exam_70] [bit] NULL,
	[Depression_30] [bit] NULL,
	[Depression_50] [bit] NULL,
	[Depression_70] [bit] NULL,
	[DM_Renal_30] [bit] NULL,
	[DM_Renal_50] [bit] NULL,
	[DM_Renal_70] [bit] NULL,
	[High_Cost_10] [bit] NULL,
	[LatestSentimentScore] [int] NULL,
	[AllSentimentScores] [varchar](250) NULL,
	[TotalVisitCount] [int] NULL,
 CONSTRAINT [PK_MainPersonalStats] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY],
 CONSTRAINT [Unique_PreLoad_cust_mvdid_monthid] UNIQUE NONCLUSTERED 
(
	[Cust_ID] ASC,
	[MVDID] ASC,
	[MemberID] ASC,
	[MonthID] ASC,
	[PCP_NPI] ASC,
	[PCP_TIN] ASC,
	[LOB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_MainPersonalStats_LastDrugDispensedDate] ON [Rules].[MainPersonalStats]
(
	[LastDrugDispensedDate] ASC
)
INCLUDE([ID],[Cust_ID],[MVDID],[MemberID],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MainPersonalStats_LastERVisit] ON [Rules].[MainPersonalStats]
(
	[LastERVisit] ASC
)
INCLUDE([Cust_ID],[MVDID],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MainPersonalStats_LastERVisit_LastPhysicianVisit] ON [Rules].[MainPersonalStats]
(
	[LastERVisit] ASC,
	[LastPhysicianVisit] ASC
)
INCLUDE([Cust_ID],[MVDID],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MainPersonalStats_LastPhysicianVisit] ON [Rules].[MainPersonalStats]
(
	[LastPhysicianVisit] ASC
)
INCLUDE([Cust_ID],[MVDID],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MainPersonalStats_Rolling12MonthERVisits] ON [Rules].[MainPersonalStats]
(
	[Rolling12MonthERVisits] ASC
)
INCLUDE([Cust_ID],[MVDID],[MonthID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthERVisits]  DEFAULT ((0)) FOR [Rolling12MonthERVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthLABVisits]  DEFAULT ((0)) FOR [Rolling12MonthLABVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthPhysicianVisits]  DEFAULT ((0)) FOR [Rolling12MonthPhysicianVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthAcuteVisits]  DEFAULT ((0)) FOR [Rolling12MonthAcuteVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthBHVisits]  DEFAULT ((0)) FOR [Rolling12MonthBHVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthNFVisits]  DEFAULT ((0)) FOR [Rolling12MonthNFVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthRehabVisits]  DEFAULT ((0)) FOR [Rolling12MonthRehabVisits]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthAllClaimCost]  DEFAULT ((0)) FOR [Rolling12MonthAllClaimCost]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_Rolling12MonthRxClaimCost]  DEFAULT ((0)) FOR [Rolling12MonthRxClaimCost]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_YTDAllClaimCost]  DEFAULT ((0)) FOR [YTDAllClaimCost]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_YTDRxClaimCost]  DEFAULT ((0)) FOR [YTDRxClaimCost]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_CreationDate]  DEFAULT (getdate()) FOR [CreationDate]
ALTER TABLE [Rules].[MainPersonalStats] ADD  CONSTRAINT [DF_MainPersonalStats_ModifyDate]  DEFAULT (getdate()) FOR [ModifyDate]