/****** Object:  Procedure [dbo].[Get_FormHROBCarePlanByID]    Committed by VersionSQL https://www.versionsql.com ******/

-- =======================================================
-- Author:		BDW 
-- Create date: 4/15/2016
-- Description:	
-- EXEC [Get_FormHROBCarePlan] 'AA007171', '13'
-- ========================================================

CREATE PROCEDURE [dbo].[Get_FormHROBCarePlanByID]
@ID varchar(20)
AS
BEGIN
	SET NOCOUNT ON;

SELECT top 1[ID]
      ,[MVDID]
      ,[CustID]
      ,[StaffInterviewing]
      ,[FormDate]
      ,[Gender]
      ,[DateOfBirth]
      ,[PLan]
      ,[ProviderIDNumber]
      ,[IncreaseKnowledge]
      ,[IncreaseKnowledgeDate]      
      ,[IncreaseComp]
      ,[IncreaseCompDate]
	  ,[SuccessOutcome]
      ,[SuccessOutcomeDate]
      ,[MemberVerbPlan]
      ,[MemberVerbPlanDate]
      ,[MemberVerbCompl]
      ,[MemberVerbComplDate]
      ,[MemberVerbMeds]
      ,[MemberVerbMedsDate]
      ,[MemVerbSelfCare]
      ,[MemVerbSelfCareDate]
      ,[MemVerbCommRes]
      ,[MemVerbCommResDate]      
      ,[MemberAvoidTobacco]
      ,[MemberAvoidTobaccoDate]
	  ,[MemberAvoidAlcohol]
      ,[MemberAvoidAlcoholDate]
	  ,[MemberAvoidDrugs]
      ,[MemberAvoidDrugsDate]
      ,[MemberAnnualFlu]
      ,[MemberAnnualFluDate]
	  ,[MemberTDAP]
      ,[MemberTDAPDate]
      ,[AssessMemKnowledge]
      ,[AssessMemUnderstanding]
      ,[PCPFollowup]
      ,[AfterHours]
      ,[ConvinientCare]
      ,[UrgentCare]
      ,[ER]
      ,[AssessSelfCare]
      ,[AssessDiet]
	  ,[ReferWIC]
      ,[ReferCommSupport]
      ,[AssessMedComp] 
	  ,[Assess17P]    
      ,[AssessTobacco]
      ,[ReferTobacco]
      ,[ReferProvider]
	  ,[AssessAlcoholDrugs]
	  ,[ReferBHP]
      ,[CommToProvider]
      ,[CommWithMemFamily]
      ,[CollWithTeam]
      ,[chkGG1]
      ,[chkGG2]
      ,[chkGG3]
      ,[chkGG4]
      ,[chkGG5]
      ,[chkGG6]
      ,[chkBDG1]
      ,[chkBDG2]
      ,[chkBDG3]
      ,[chkBDG4]
      ,[chkBDG5]
      ,[chkBDG6]
      ,[chkBDG7]
      ,[chkBDG8]
      ,[chkBDG9]
      ,[chkBDG10]   
      ,[chkPCP1]
      ,[chkPCP2]
      ,[chkPCP3]
      ,[chkPCP4]
      ,[chkPCP5]
      ,[chkPCP6] 
	  ,[chkPCP7] 
	  ,[chkPCP8] 
	  ,[chkPCP9] 
	  ,[chkPCP10] 
	  ,[chkPCP11] 
	  ,[chkPCP12] 
	  ,[chkPCP13] 
	  ,[chkPCP14] 
	  ,[chkPCP15] 
	  ,[ContinueCare]
	  ,[EstablishFreq]
	  ,[MemDischarged]
	  ,[MemDischargedReason]					
	  ,f.[Created]
	  ,f.[CreatedBy]
	  ,f.[ModifiedDate]
	  ,f.[ModifiedBy]
	  ,d.FirstName
	  ,d.LastName
  FROM [FormHROBCarePlan] F
  Left JOIN MainPersonalDetails d ON d.ICENUMBER = F.MVDID
  LEFT JOIN MainInsurance m ON m.ICENUMBER = F.MVDID 
  where F.ID = @ID
  order by f.FormDate desc
END