/****** Object:  Procedure [dbo].[Set_HPAlertGroup]    Committed by VersionSQL https://www.versionsql.com ******/

-- =============================================
-- Author:		sw
-- Create date: 9/23/2009
-- Description:	 Creates an instance of Alert Group
--		AgentList - list of comma separated items
-- =============================================
CREATE PROCEDURE [dbo].[Set_HPAlertGroup]
	@Name varchar(50),
	@Description varchar(500),
	@CustomerId int,
	@AgentList varchar(max),
	@Active bit,
	@Result int output
AS
BEGIN
	SET NOCOUNT ON;

	declare @groupId int, @tempId varchar(50)

	-- holds the result of values split from the input strings
	create table #temp (data varchar(50), isProcessed bit default(0))

	if not exists(select Name from HPAlertGroup where Name = @Name and Cust_Id = @CustomerId)
	begin
		-- create record in main alert table
		insert into dbo.HPAlertGroup (Cust_Id,Name,Description,Active)
		values(@CustomerId, @Name, @Description, @Active)

		-- get autogenerated ID for the group
		select @groupId = @@IDENTITY

		-- insert records into tables related to the group

		-- AGENT
		if(len(isnull(@AgentList,'')) > 0)
		begin
			insert into #temp (data)
				select data from dbo.split(@AgentList,',')

			-- insert records into Group_Agent relation table
			while exists (select data from #temp where isProcessed = 0)
			begin
				select top 1 @tempId = data from #temp where isProcessed = 0
				
				insert into Link_HPAlertGroupAgent (Group_ID, Agent_ID)
					values (@groupId, @tempId)

				delete from #temp where data = @tempId
			end
		end

		select @result = 0
	end
	else
	begin
		select @result = -1
	end
	
	drop table #temp	
END