/****** Object:  Procedure [dbo].[Set_FormAsthmaAssessment]    Committed by VersionSQL https://www.versionsql.com ******/

-- =============================================
-- Author:		<Author,,Name>
-- Create date: 5/06/2015
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[Set_FormAsthmaAssessment]
	@MVDID varchar(20),
	@CustID varchar(20),
	@StaffInterviewing varchar(50),
	@FormDate date,
	@Gender Char(1) ,
	@DateOfBirth datetime  ,
	@PLan varchar (50),
	@ProviderIDNumber varchar(20),
	@Address varchar (150),
	@City varchar (50),
	@State varchar (50),
	@Zip varchar (10),
	@MemberPhone varchar (13),
	@MemberOtherPhone varchar (13)= NULL,
	@MemberExt varchar (4) =NULL,
	@MemberEmail varchar (150) =NULL,
	@ParentLegalGuardian varchar (150)= NULL,
	@GuardianPhone  varchar(13)= NULL,
	@GuardianOtherPhone varchar (13) =NULL,
	@GuardianExt varchar (4) =NULL,
	@IntroductionOfCMRole  bit,
	@MemberAgreeableToCMservices bit = NULL,
	@CMServicesReason varchar (60)= NULL,
	@PrimaryCareProvider bit,
	@ProviderContactNumber varchar(13)= NULL,
	@DateofLastVisit datetime = NULL,
	@AshthmaSymptoms varchar(150)= NULL,
	@AsthmaSymptomsAreYouOrYourChildHaving varchar(150)= NULL,
	@AgeofPrimaryAsthmaDiagnosis int  =NULL,
	@WhoManagesAsthma varchar (150) =NULL,
	@SpecialistProviderNameContactNumber varchar(150)= NULL,
	@HosptializationInPastyear bit,
	@Location varchar (150) =NULL,
	@HosptializationOtherLocation varchar (150)= NULL,
	@HosptializationDate datetime = NULL ,
	@NumberOfEmergencyDepartmentEDVisitsPast6Months int = NULL ,
	@EDVisitsLocation varchar (150) =NULL,
	@EDVisitsOtherLocation varchar (150)= NULL,
	@EDVisitInNetworkFacility bit,
	@Excersie bit ,
	@RespiratoryInfections bit  ,
	@SeasonalChanges bit  ,
	@Cold bit ,
	@Humidification bit ,
	@Allergans bit  ,
	@Dust bit ,
	@Mold bit,
	@Carpet bit,
	@Fragrances bit,
	@Pets bit,
	@Pollen bit,
	@Cedar bit,
	@Chemicals bit,
	@DoesAnyoneinYourHouseholdSmoke bit,
	@SmokingCessation bit,
	@DoYouorYourChildReceiveTheFLUVaccineSeasonally bit,
	@FrequencyofprovidervisitsRelatedtoAsthmaManagement varchar (200) =NULL,
	@DailyMaintenanceMedicaitons varchar (200)=null ,
	@Nebilzer bit  =NULL ,
	@RescueInhaler bit ,
	@HowOftenUsed Varchar(150) =null,
	@PeakFlowMeter bit,
	@Spacer bit,
	@DateOflastPulmonryFunctionTest varchar(150)= NULL ,
	@SchoolInformedOfActionPlanForYourChild bit,
	@InhalerAtSchool bit,
	@SpecialNotes varchar (300)= NULL ,
	@Result int = -1 output
AS
BEGIN
	SET NOCOUNT ON;

	declare @FormID int, @UserType varchar(10)

	INSERT INTO FormAsthmaAssessment
   	 ([MVDID],
	[CustID],
	[StaffInterviewing] ,
	[FormDate],
	[Gender],
	[DateOfBirth] ,
	[PLan] ,
	[ProviderIDNumber],
	[Address] ,
	[City] ,
	[State] ,
	[Zip] ,
	[MemberPhone],
	[MemberOtherPhone] ,
	[MemberExt] ,
	[MemberEmail],
	[ParentLegalGuardian],
	[GuardianPhone] ,
	[GuardianOtherPhone],
	[GuardianExt] ,
	[IntroductionOfCMRole] ,
	[MemberAgreeableToCMservices] ,
	[CMServicesReason] ,
	[PrimaryCareProvider] ,
	[ProviderContactNumber],
	[DateofLastVisit] ,
	[AshthmaSymptoms] ,
	[AsthmaSymptomsAreYouOrYourChildHaving] ,
	[AgeofPrimaryAsthmaDiagnosis],
	[WhoManagesAsthma] ,
	[SpecialistProviderNameContactNumber] ,
	[HosptializationInPastyear] ,
	[Location] ,
	[HosptializationOtherLocation] ,
	[HosptializationDate]  ,
	[NumberOfEmergencyDepartmentEDVisitsPast6Months],
	[EDVisitsLocation] ,
	[EDVisitsOtherLocation] ,
	[EDvisitInNetworkFacility] ,
	[Excersie],
	[RespiratoryInfections] ,
	[SeasonalChanges]  ,
	[Cold],
	[Humidification],
	[Allergans]  ,
	[Dust]  ,
	[Mold]  ,
	[Carpet]  ,
	[Fragrances]  ,
	[Pets] ,
	[Pollen]  ,
	[Cedar]  ,
	[Chemicals]  ,
	[DoesAnyoneinYourHouseholdSmoke]  ,
	[SmokingCessation]  ,
	[DoYouorYourChildReceiveTheFLUVaccineSeasonally]  ,
	[FrequencyofprovidervisitsRelatedtoAsthmaManagement] ,
	[DailyMaintenanceMedicaitons] ,
	[Nebilzer] ,
	[RescueInhaler] ,
	[HowOftenUsed] ,
	[PeakFlowMeter] ,
	[Spacer]  ,
	[DateOflastPulmonryFunctionTest]  ,
	[SchoolInformedOfActionPlanForYourChild]  ,
	[InhalerAtSchool]  ,
	[SpecialNotes],
	[Created],
    [CreatedBy],
    [ModifiedDate],
    [ModifiedBy])
     VALUES
     (
			@MVDID,
			@CustID,
			@StaffInterviewing ,
			@FormDate,
			@Gender,
			Convert(varchar(10),@DateOfBirth,101),
			@PLan ,
			@ProviderIDNumber,
			@Address ,
			@City ,
			@State ,
			@Zip ,
			@MemberPhone,
			@MemberOtherPhone ,
			@MemberExt ,
			@MemberEmail,
			@ParentLegalGuardian,
			@GuardianPhone ,
			@GuardianOtherPhone,
			@GuardianExt ,
			@IntroductionOfCMRole ,
			@MemberAgreeableToCMservices ,
			@CMServicesReason ,
			@PrimaryCareProvider ,
			@ProviderContactNumber,
			CONVERT(VARCHAR(10),cast(@DateofLastVisit as date),101)  ,
			@AshthmaSymptoms ,
			@AsthmaSymptomsAreYouOrYourChildHaving ,
			@AgeofPrimaryAsthmaDiagnosis,
			@WhoManagesAsthma ,
			@SpecialistProviderNameContactNumber ,
			@HosptializationInPastyear ,
			@Location ,
			@HosptializationOtherLocation ,
			CONVERT(VARCHAR(10),cast(@HosptializationDate as date),101)  ,
			@NumberOfEmergencyDepartmentEDVisitsPast6Months,
			@EDVisitsLocation ,
			@EDVisitsOtherLocation ,
			@EDvisitInNetworkFacility ,
			@Excersie,
			@RespiratoryInfections ,
			@SeasonalChanges  ,
			@Cold,
			@Humidification,
			@Allergans  ,
			@Dust  ,
			@Mold  ,
			@Carpet  ,
			@Fragrances  ,
			@Pets ,
			@Pollen  ,
			@Cedar  ,
			@Chemicals  ,
			@DoesAnyoneinYourHouseholdSmoke  ,
			@SmokingCessation  ,
			@DoYouorYourChildReceiveTheFLUVaccineSeasonally  ,
			@FrequencyofprovidervisitsRelatedtoAsthmaManagement ,
			@DailyMaintenanceMedicaitons ,
			@Nebilzer ,
			@RescueInhaler ,
			@HowOftenUsed,
			@PeakFlowMeter ,
			@Spacer  ,
			@DateOflastPulmonryFunctionTest,
			@SchoolInformedOfActionPlanForYourChild  ,
			@InhalerAtSchool  ,
			@SpecialNotes,
			@FormDate,
			@StaffInterviewing,
			GETDATE(),
           @StaffInterviewing
     )
     
	   declare @insMemberID varchar(20), @noteText varchar(1000)
     
     select @insMemberID = InsMemberId from Link_MemberId_MVD_Ins where MVDId = @MVDID
     select @noteText = 'Asthma Assessment Form Saved. '

	 if exists(select top 1 * from MDUser where Username =  @StaffInterviewing)
     begin
		set @UserType = 'MD'
	end
	else
	begin
		set @UserType = 'HP'		
	end
	select @FormID = @@IDENTITY

	insert into HPAlertNote (MVDID,Note,AlertStatusID,datecreated,createdby,CreatedByType,
		datemodified,modifiedby,ModifiedByType,SendToHP,SendToPCP,SendToNurture,SendToNone,LinkedFormType,LinkedFormID)
	values(@MVDID,@noteText,0,GETUTCDATE(),@StaffInterviewing,@UserType,GETUTCDATE(),@StaffInterviewing,@UserType,0,0,0,0,'AA',@FormID)

    
     set @Result = @FormID
END