/****** Object:  Procedure [dbo].[Set_FormDiabetesAssessment]    Committed by VersionSQL https://www.versionsql.com ******/

-- =============================================
-- Author:		<Author,,Name>
-- Create date: 5/06/2015
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[Set_FormDiabetesAssessment]
	@MVDID varchar(20),
	@CustID  varchar(20),
	@StaffInterviewing varchar(50),
	@FormDate date,
	@Gender Char(1) ,
	@DateOfBirth datetime  ,
	@PLan varchar (50),
	@ProviderIDNumber varchar(30) ,
	@Address varchar (150),
	@City varchar (50),
	@State varchar (50),
	@Zip varchar (10),
	@MemberPhone varchar (13),
	@MemberOtherPhone varchar (13)= NULL,
	@MemberExt varchar (4) =NULL,
	@MemberEmail varchar (150) =NULL,
	@ParentLegalGuardian varchar (150)= NULL,
	@GuardianPhone  varchar(13)= NULL,
	@GuardianOtherPhone varchar (13) =NULL,
	@GuardianExt varchar (4) =NULL,
	@IntroductionOfCMRole  bit,
	@MemberAgreeToCMservices bit = NULL,
	@CMServicesReason varchar (100)= NULL,
	@PrimaryCareProvider bit,
	@ProviderContactNumber varchar(13)= NULL,
	@DateofLastVisit date = NULL,
	@Type1 bit=Null ,
	@Type2 bit=NULL,
	@ChildTakeInsulin bit=NULL ,
	@ChildInsulinDetails varchar (100) =NULL,
	@OralHypoglycemicAgents varchar(150)= NULL,
	@AgeatDiagnosis int=NULL,
	@ChildsDiabetesName varchar (150) =NULL,
	@ChildsDiabetesLocation varchar (150) =NULL,
	@ChildsDiabetesContact varchar (13) =NULL,
	@SpecialistDiabetesName varchar (150) =NULL,
	@SpecialistDiabetesContact varchar (13) =NULL,
	@SpecialistDiabetesName1 varchar (150) =NULL,
	@SpecialistDiabetesContact1 varchar (13) =NULL,
	@DoctorforDiabetesManagement varchar (150) =NULL,
	@HospPastYear bit=NULL,
	@HospLocation varchar (150) =NULL,
	@HospOtherLocation varchar (150)= NULL,
	@HospDate datetime = NULL ,
	@NumberOfEDVisitsPast6Months int = NULL ,
	@EDVisitsLocation varchar (150) =NULL,
	@EDVisitsOtherLocation varchar (150)= NULL,
	@Dates varchar(150) =NULL,
	@BloodGlucoseLevels varchar (150)= NULL,
	@BloodGlucoseRange varchar (150)= NULL,
	@HbA1clevel  varchar (150)= NULL,
	@CholesterolScreen bit=null ,
	@CholesterolScreenResult  varchar (300)= NULL,
	 @BloodPressureChecked  bit =NULL,
	 @BloodPressureResults  varchar(300)= NULL,
	 @VisionExam  bit =NULL,
	 @MediInstructions bit=NULL,
	 @RoutineVisit bit=null ,
	 @LossOfSensation  bit =NULL,
	 @ClosedTtoeShoes  bit =NULL,
	 @DMEducation bit=null ,
	 @FLUVaccineSeasonally  bit =NULL,
	 @HowDescribeChildDM  varchar(300)= NULL,
	 @HowOftenChildDM varchar(300) =NULL,
	 @DoctorAppointments  bit =NULL,
	 @DiffDiabetesmanagement  varchar(300)= NULL,
	 @SpecialNotes  varchar(300)= NULL,
	 @Created  date= NULL,
	 @CreatedBy  varchar(50)= NULL,
	 @ModifiedDate  date= NULL,
	 @ModifiedBy  varchar(50)= NULL,
	@Result int = -1 output
AS
BEGIN
	SET NOCOUNT ON;

	declare @FormID int, @UserType varchar(10)

	INSERT INTO FormDiabetesAssessment
    ([MVDID],
	[CustID],
	[StaffInterviewing] ,
	[FormDate],
	[Gender],
	[DateOfBirth] ,
	[PLan] ,
	[ProviderIDNumber],
	[Address] ,
	[City] ,
	[State] ,
	[Zip] ,
	[MemberPhone],
	[MemberOtherPhone] ,
	[MemberExt] ,
	[MemberEmail],
	[ParentLegalGuardian],
	[GuardianPhone] ,
	[GuardianOtherPhone],
	[GuardianExt] ,
	[IntroductionOfCMRole] ,
	[MemberAgreeToCMservices] ,
	[CMServicesReason] ,
	[PrimaryCareProvider] ,
	[ProviderContactNumber],
	[DateofLastVisit] ,
	[Type1] ,
	[Type2] ,
	[ChildTakeInsulin] ,
	[ChildInsulinDetails],
	[OralHypoglycemicAgents]  ,
	[AgeatDiagnosis]  ,
	[ChildsDiabetesName] ,
	[ChildsDiabetesLocation]  ,
	[ChildsDiabetesContact] ,
	[SpecialistDiabetesName] ,
	[SpecialistDiabetesContact] ,
	[SpecialistDiabetesName1] ,
	[SpecialistDiabetesContact1] ,
	[DoctorforDiabetesManagement],
	[HospPastYear] ,
	[HospLocation]  ,
	[HospOtherLocation]  ,
	[HospDate],
	[NumberOfEDVisitsPast6Months],
	[EDVisitsLocation]  ,
	[EDVisitsOtherLocation]  ,
	[Dates]  ,
	[BloodGlucoseLevels] ,
	[Bloodglucoserange] ,
	[HbA1clevel] ,
	[CholesterolScreen] ,
	[CholesterolScreenResult] ,
	[BloodPressureChecked] ,
	[BloodPressureResults] ,
	[VisionExam] ,
	[MediInstructions],
	[RoutineVisit] ,
	[LossOfSensation] ,
	[ClosedTtoeShoes] ,
	[DMEducation] ,
	[FLUVaccineSeasonally] ,
	[HowDescribeChildDM]  ,
	[HowOftenChildDM] ,
	[DoctorAppointments] ,
	[DiffDiabetesmanagement] ,
	[SpecialNotes] ,
	[Created] ,
	[CreatedBy]  ,
	[ModifiedDate] ,
	[ModifiedBy])
     VALUES
     (
			@MVDID,
			@CustID,
			@StaffInterviewing ,
			@FormDate,
			@Gender,
			Convert(varchar(10),@DateOfBirth,101),
			@PLan ,
			@ProviderIDNumber,
			@Address ,
			@City ,
			@State ,
			@Zip ,
			@MemberPhone,
			@MemberOtherPhone ,
			@MemberExt ,
			@MemberEmail,
			@ParentLegalGuardian,
			@GuardianPhone ,
			@GuardianOtherPhone,
			@GuardianExt ,
			@IntroductionOfCMRole ,
			@MemberAgreeToCMservices,
			@CMServicesReason ,
			@PrimaryCareProvider ,
			@ProviderContactNumber,
			CONVERT(VARCHAR(10),cast(@DateofLastVisit as date),101),
			@Type1,
			@Type2,
			@ChildTakeInsulin,
			@ChildInsulinDetails,
			@OralHypoglycemicAgents,
			@AgeatDiagnosis,
			@ChildsDiabetesName,
			@ChildsDiabetesLocation,
			@ChildsDiabetesContact,
			@SpecialistDiabetesName ,
			@SpecialistDiabetesContact,
			@SpecialistDiabetesName1,
			@SpecialistDiabetesContact1,
			@DoctorforDiabetesManagement,
			@HospPastYear,
			@HospLocation,
			@HospOtherLocation,
			@HospDate,
			@NumberOfEDVisitsPast6Months,
			@EDVisitsLocation,
			@EDVisitsOtherLocation,
			@Dates,
			@BloodGlucoseLevels ,
			@BloodGlucoseRange,
			@HbA1clevel  ,
			@CholesterolScreen,
			@CholesterolScreenResult,
			@BloodPressureChecked,
			@BloodPressureResults,
			@VisionExam,
			@MediInstructions,
			@RoutineVisit,
			@LossOfSensation,
			@ClosedTtoeShoes,
			@DMEducation,
			@FLUVaccineSeasonally,
			@HowDescribeChildDM,
			@HowOftenChildDM,
			@DoctorAppointments,
			@DiffDiabetesmanagement,
			@SpecialNotes,
			@FormDate,
			@StaffInterviewing,
			GETDATE(),
			@StaffInterviewing
     )
     
	 declare @insMemberID varchar(20), @noteText varchar(1000)
     select @insMemberID = InsMemberId from Link_MemberId_MVD_Ins where MVDId = @MVDID
     select @noteText = 'Diabetes Assessment Form Saved. '

	 if exists(select top 1 * from MDUser where Username =  @StaffInterviewing)
     begin
		set @UserType = 'MD'
	end
	else
	begin
		set @UserType = 'HP'		
	end
	select @FormID = @@IDENTITY

	insert into HPAlertNote (MVDID,Note,AlertStatusID,datecreated,createdby,CreatedByType,
		datemodified,modifiedby,ModifiedByType,SendToHP,SendToPCP,SendToNurture,SendToNone,LinkedFormType,LinkedFormID)
	values(@MVDID,@noteText,0,GETUTCDATE(),@StaffInterviewing,@UserType,GETUTCDATE(),@StaffInterviewing,@UserType,0,0,0,0,'DIA',@FormID)

    
     set @Result = @FormID
END