/****** Object:  Procedure [Rules].[Set_MainPersonalStats_Measures]    Committed by VersionSQL https://www.versionsql.com ******/

--Drop proc Rules.Set_MainPersonalStats_Measures

CREATE PROC [Rules].[Set_MainPersonalStats_Measures]
(
	@CustID INT = NULL
)
AS
BEGIN

SET NOCOUNT ON;
----------------------------------------------------------------------------------------------------------------------
-- Author: PPetluri	
-- Date			Name				Comments														
-- 02/27/17		PPetluri			Created to update and insert data into Rules.MainPersonalStats table for MaxMonthID
----------------------------------------------------------------------------------------------------------------------
--Declare @CustID		INT = NULL
--SET @CustID = 11

	IF OBJECT_ID('TempDB.dbo.#Temp_UPD_MainPersonalStats','U') is not null
	Drop table #Temp_UPD_MainPersonalStats
	Create table #Temp_UPD_MainPersonalStats
	(
		ID					BIGINT	IDENTITY(1,1),
		Cust_ID				INT,
		MVDID				VARCHAR(50),
		MemberID			VARCHAR(50),
		MonthID				VARCHAR(6),
		PCP_TIN				VARCHAR(50),
		PCP_NPI				VARCHAR(50),
		LOB					VARCHAR(20),
		IsW15				BIT,
		IsW15_Mod1			BIT,
		IsW34				BIT,
		IsAWC				BIT,
		IsLSC				BIT,
		IsBCS				BIT,
		IsCCS				BIT,
		IsCOL				BIT,
		IsCAP				BIT,
		IsASM				BIT,
		IsCIS				BIT,
		IsCWP				BIT,
		IsAMR				BIT,
		IsAMR_Mod1			BIT,
		IsFUH7				BIT,
		IsFUH30				BIT,
		IsURI				BIT,
		IsADD_Init			BIT,
		IsADD_CM			BIT,
		IsPPC1				BIT,
		IsPPC2				BIT,
		IsCISCMB2			BIT,
		IsCISCMB3			BIT,
		IsCISCMB4			BIT,
		IsCISCMB5			BIT,
		IsCISCMB6			BIT,
		IsCISCMB7			BIT,
		IsCISCMB8			BIT,
		IsCISCMB9			BIT,
		IsCISCMB10			BIT,
		IsCISDTP			BIT,
		IsCISHEPA			BIT,
		IsCISHEPB			BIT,
		IsCISHIB			BIT,
		IsCISINFL			BIT,
		IsCISMMR			BIT,
		IsCISIPV			BIT,
		IsCISPNEU			BIT,
		IsCISROTA			BIT,
		IsCISVZV			BIT,
		IsCDC1				BIT,
		IsCDC2				BIT,
		IsCDC3				BIT,
		IsCDC4				BIT,
		IsCDC7				BIT,
		IsCDC9				BIT,
		IsCDC10				BIT,
		IsWCC1				BIT,
		IsWCC2				BIT,
		IsWCC3				BIT,
		IsCBP				BIT,
		IsMMA1A				BIT,
		IsMMA1B				BIT,
		IsMMA2A				BIT,
		IsMMA2B				BIT,
		IsMMA3A				BIT,
		IsMMA3B				BIT,
		IsMMA4A				BIT,
		IsMMA4B				BIT,
		IsIMAMEN			BIT,
		IsIMATD				BIT,
		IsIMAHPV			BIT,
		IsABA				BIT,
		IsAAB				BIT,
		IsAMM1				BIT,
		IsAMM2				BIT,
		IsNCS				BIT,
		IsASM1				BIT,
		IsASM2				BIT,
		IsASM3				BIT,
		IsASM4				BIT,
		IsIMACMB1			BIT,
		IsIMACMB2			BIT
	CONSTRAINT [PK_Temp_UPD_MainPersonalStats] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	))						

	INSERT INTO #Temp_UPD_MainPersonalStats(Cust_ID, MVDID,MemberID,PCP_TIN, PCP_NPI, LOB, MonthID,IsW15,IsW15_Mod1,IsW34,IsAWC,IsLSC,IsBCS,IsCCS,IsCOL,IsCAP,IsASM,IsCIS,IsCWP,IsAMR,IsAMR_Mod1,IsFUH7
									,IsFUH30,IsURI,IsADD_Init,IsADD_CM,IsPPC1,IsPPC2,IsCISCMB2,IsCISCMB3,IsCISCMB4,IsCISCMB5,IsCISCMB6,IsCISCMB7,IsCISCMB8,IsCISCMB9,IsCISCMB10,IsCISDTP,IsCISHEPA,
									IsCISHEPB,IsCISHIB,IsCISINFL,IsCISMMR,IsCISIPV,IsCISPNEU,IsCISROTA,IsCISVZV,IsCDC1,IsCDC4,IsWCC1,IsWCC2,IsWCC3,IsCBP,IsCDC2,IsCDC3,IsCDC7,IsCDC9,IsCDC10,IsMMA1A,
									IsMMA1B,IsMMA2A,IsMMA2B,IsMMA3A,IsMMA3B,IsMMA4A,IsMMA4B,IsIMAMEN,IsIMATD,IsIMAHPV,IsABA,IsAAB,IsAMM1,IsAMM2,IsNCS,IsASM1,IsASM2,IsASM3,IsASM4,IsIMACMB1,IsIMACMB2)	

	SELECT DISTINCT Pvt.CustID as Cust_ID, Pvt.MVDID, Pvt.MemberID, Pvt.PCP_TIN, Pvt.PCP_NPI, Pvt.LOB, pvt.MonthID, 
		   CAST(pvt.W15 as BIT) as IsW15,CAST(pvt.W15_Mod1 as BIT) W15_Mod1,CAST(W34 as BIT) as IsW34,CAST(AWC as BIT) as IsAWC,CAST(LSC as BIT) as IsLSC,CAST(BCS  as BIT)as IsBCS,CAST(CCS  as BIT)as IsCCS,
		   CAST(COL as BIT) as IsCOL,CAST(CAP as BIT) as IsCAP,CAST(ASM as BIT) as IsASM, CAST(CIS as BIT) as IsCIS,CAST(CWP as BIT) as IsCWP,CAST(AMR as BIT) as IsAMR,CAST(AMR_Mod1 as BIT) as IsAMR_Mod1,
		   CAST(FUH7  as BIT)as IsFUH7,CAST(FUH30 as BIT) as IsFUH30,CAST(URI as BIT) as IsURI,CAST(ADD_Init as BIT) as IsADD_Init,CAST(ADD_CM as BIT) as IsADD_CM,CAST(PPC1 as BIT) as IsPPC1,
		   CAST(PPC2  as BIT)as IsPPC2,CAST(CISCMB2 as BIT) as IsCISCMB2,CAST(CISCMB3 as BIT) as IsCISCMB3,CAST(CISCMB4 as BIT) as IsCISCMB4,CAST(CISCMB5 as BIT) as IsCISCMB5,CAST(CISCMB6 as BIT) as IsCISCMB6,
		   CAST(CISCMB7 as BIT) as IsCISCMB7,CAST(CISCMB8 as BIT) as IsCISCMB8,CAST(CISCMB9 as BIT) as IsCISCMB9,CAST(CISCMB10 as BIT) as IsCISCMB10,CAST(CISDTP as BIT) as isCISDTP,CAST(CISHEPA as BIT) as IsCHEPA,
		   CAST(CISHEPB as BIT) as IsCISHEPB,CAST(CISHIB as BIT) as IsCISHIB,CAST(CISINFL as BIT) as IsCISINFL,CAST(CISMMR as BIT) as IsCISMMR,CAST(CISIPV as BIT) as IsCISIPV,CAST(CISPNEU as BIT) as IsCISPNEU,CAST(CISROTA as BIT) as IsCISROTA,
		   CAST(CISVZV as BIT) as IsCISVZV, CAST(CDC1 as BIT) as IsCDC1,CAST(CDC4 as BIT) as IsCDC4,CAST(WCC1 as BIT) as IsWCC1,CAST(WCC2 as BIT) IsWCC2,CAST(WCC3 as BIT) as IsWCC3,CAST(CBP as BIT) as IsCBP,CAST(CDC2 as BIT) as IsCDC2,
		   CAST(CDC3 as BIT) as IsCDC3,CAST(CDC7 as BIT) as IsCDC7,CAST(CDC9 as BIT) as IsCDC9,CAST(CDC10 as BIT) as IsCDC10,CAST(MMA1A as BIT) as IsMMA1A,CAST(MMA1B as BIT) as IsMMA1B,CAST(MMA2A as BIT) as IsMMA2A,
		   CAST(MMA2B as BIT) as IsMMA2B,CAST(MMA3A as BIT) as IsMMA3A,CAST(MMA3B as BIT) as IsMMA3B,CAST(MMA4A as BIT) as IsMMA4A,CAST(MMA4B as BIT) as IsMMA4B,CAST(IMAMEN as BIT) as IsIMAMEN,
		   CAST(IMATD as BIT) as IsIMATD,CAST(IMAHPV as BIT) as IsIMAHPV,CAST(ABA as BIT) as IsABA,CAST(AAB as BIT) as IsAAB,CAST(AMM1 as BIT) as IsAMM1,CAST(AMM2 as BIT) as IsAMM2,CAST(NCS as BIT) as IsNCS,
		   CAST(ASM1 as BIT) as IsASM1,CAST(ASM2 as BIT) as IsASM2,CAST(ASM3 as BIT) as IsASM3,CAST(ASM4 as BIT) as IsASM4,CAST(IMACMB1 as BIT) as IsIMACMB1,CAST(IMACMB2 as BIT) as IsIMACMB2
	 FROM (
	SELECT DISTINCT h.custID, h.MVDID, h.memberid, h.PCP_NPI, h.PCP_TIN, h.LOB , h.monthid, 1 as value, lh.Abbreviation 
	FROM Final_HEDIS_Member_FULL h JOIN LookupHEDIS lh on h.TestID = lh.id 
	INNER JOIN Rules.MainPersonalStats R ON R.Cust_ID = h.CustID and R.monthID = h.MonthID and R.MVDID = h.MVDID and R.MemberID = h.MemberID
	INNER JOIN HPCustomer C ON C.Cust_ID = h.CustID
	where (h.CustID = @CustID or @CustID is NULL) and h.monthID = (Select MAX(h1.MonthID) from Final_HEDIS_Member_FULL h1 Where h1.CustID = h.CustID) and C.Active = 1
	) P
	pivot (max(p.value) for Abbreviation in 
		(
			W15,
			W15_Mod1,
			W34,
			AWC,
			LSC,
			BCS,
			CCS,
			COL,
			CAP,
			ASM,
			CIS,
			CWP,
			AMR,
			AMR_Mod1,
			FUH7,
			FUH30,
			URI,
			ADD_Init,
			ADD_CM,
			PPC1,
			PPC2,
			CISCMB2,
			CISCMB3,
			CISCMB4,
			CISCMB5,
			CISCMB6,
			CISCMB7,
			CISCMB8,
			CISCMB9,
			CISCMB10,
			CISDTP,
			CISHEPA,
			CISHEPB,
			CISHIB,
			CISINFL,
			CISMMR,
			CISIPV,
			CISPNEU,
			CISROTA,
			CISVZV,
			CDC1,
			CDC2,
			CDC3,
			CDC4,
			CDC7,
			CDC9,
			CDC10,
			WCC1,
			WCC2,
			WCC3,
			CBP,
			MMA1A,
			MMA1B,
			MMA2A,
			MMA2B,
			MMA3A,
			MMA3B,
			MMA4A,
			MMA4B,
			IMAMEN,
			IMATD,
			IMAHPV,
			ABA,
			AAB,
			AMM1,
			AMM2,
			NCS,
			ASM1,
			ASM2,
			ASM3,
			ASM4,
			IMACMB1,
			IMACMB2
	)) as pvt

	---- Update if Exists
	UPDATE  R
	SET R.PCP_TIN = T.PCP_TIN,
		R.PCP_NPI = T.PCP_NPI,
		R.LOB = T.LOB,
		R.IsW15 = 	T.IsW15,
		R.IsW15_Mod1 = 	T.IsW15_Mod1,
		R.IsW34 = 	T.IsW34,
		R.IsAWC = 	T.IsAWC,
		R.IsLSC = 	T.IsLSC,
		R.IsBCS = 	T.IsBCS,
		R.IsCCS = 	T.IsCCS,
		R.IsCOL = 	T.IsCOL,
		R.IsCAP = 	T.IsCAP,
		R.IsASM = 	T.IsASM,
		R.IsCIS = 	T.IsCIS,
		R.IsCWP = 	T.IsCWP,
		R.IsAMR = 	T.IsAMR,
		R.IsAMR_Mod1 = 	T.IsAMR_Mod1,
		R.IsFUH7 = 	T.IsFUH7,
		R.IsFUH30 = 	T.IsFUH30,
		R.IsURI = 	T.IsURI,
		R.IsADD_Init = 	T.IsADD_Init,
		R.IsADD_CM = 	T.IsADD_CM,
		R.IsPPC1 = 	T.IsPPC1,
		R.IsPPC2 = 	T.IsPPC2,
		R.IsCISCMB2 = 	T.IsCISCMB2,
		R.IsCISCMB3 = 	T.IsCISCMB3,
		R.IsCISCMB4 = 	T.IsCISCMB4,
		R.IsCISCMB5 = 	T.IsCISCMB5,
		R.IsCISCMB6 = 	T.IsCISCMB6,
		R.IsCISCMB7 = 	T.IsCISCMB7,
		R.IsCISCMB8 = 	T.IsCISCMB8,
		R.IsCISCMB9 = 	T.IsCISCMB9,
		R.IsCISCMB10 = 	T.IsCISCMB10,
		R.IsCISDTP = 	T.IsCISDTP,
		R.IsCISHEPA = 	T.IsCISHEPA,
		R.IsCISHEPB = 	T.IsCISHEPB,
		R.IsCISHIB = 	T.IsCISHIB,
		R.IsCISINFL = 	T.IsCISINFL,
		R.IsCISMMR = 	T.IsCISMMR,
		R.IsCISIPV = 	T.IsCISIPV,
		R.IsCISPNEU = 	T.IsCISPNEU,
		R.IsCISROTA = 	T.IsCISROTA,
		R.IsCISVZV = 	T.IsCISVZV,
		R.IsCDC1 = 	T.IsCDC1,
		R.IsCDC2 = 	T.IsCDC2,
		R.IsCDC3 = 	T.IsCDC3,
		R.IsCDC4 = 	T.IsCDC4,
		R.IsCDC7 = 	T.IsCDC7,
		R.IsCDC9 = 	T.IsCDC9,
		R.IsCDC10 = 	T.IsCDC10,
		R.IsWCC1 = 	T.IsWCC1,
		R.IsWCC2 = 	T.IsWCC2,
		R.IsWCC3 = 	T.IsWCC3,
		R.IsCBP = 	T.IsCBP,
		R.IsMMA1A = 	T.IsMMA1A,
		R.IsMMA1B = 	T.IsMMA1B,
		R.IsMMA2A = 	T.IsMMA2A,
		R.IsMMA2B = 	T.IsMMA2B,
		R.IsMMA3A = 	T.IsMMA3A,
		R.IsMMA3B = 	T.IsMMA3B,
		R.IsMMA4A = 	T.IsMMA4A,
		R.IsMMA4B = 	T.IsMMA4B,
		R.IsIMAMEN = 	T.IsIMAMEN,
		R.IsIMATD = 	T.IsIMATD,
		R.IsIMAHPV = 	T.IsIMAHPV,
		R.IsABA = 	T.IsABA,
		R.IsAAB = 	T.IsAAB,
		R.IsAMM1 = 	T.IsAMM1,
		R.IsAMM2 = 	T.IsAMM2,
		R.IsNCS = 	T.IsNCS,
		R.IsASM1 = 	T.IsASM1,
		R.IsASM2 = 	T.IsASM2,
		R.IsASM3 = 	T.IsASM3,
		R.IsASM4 = 	T.IsASM4,
		R.IsIMACMB1 = 	T.IsIMACMB1,
		R.IsIMACMB2 = 	T.IsIMACMB2
	-- Select R.* 
	FROM #Temp_UPD_MainPersonalStats T JOIN Rules.MainPersonalStats R ON R.Cust_ID = T.Cust_ID and R.monthID = T.MonthID and R.MVDID = T.MVDID and R.MemberID = T.MemberID AND R.PCP_TIN = T.PCP_TIN and R.PCP_NPI = T.PCP_NPI and R.LOB = T.LOB


	---- Insert if not exists
	INSERT INTO Rules.MainPersonalStats(Cust_ID, MVDID,MemberID,PCP_TIN, PCP_NPI, LOB, MonthID,IsW15,IsW15_Mod1,IsW34,IsAWC,IsLSC,IsBCS,IsCCS,IsCOL,IsCAP,IsASM,IsCIS,IsCWP,IsAMR,IsAMR_Mod1,IsFUH7
									,IsFUH30,IsURI,IsADD_Init,IsADD_CM,IsPPC1,IsPPC2,IsCISCMB2,IsCISCMB3,IsCISCMB4,IsCISCMB5,IsCISCMB6,IsCISCMB7,IsCISCMB8,IsCISCMB9,IsCISCMB10,IsCISDTP,IsCISHEPA,
									IsCISHEPB,IsCISHIB,IsCISINFL,IsCISMMR,IsCISIPV,IsCISPNEU,IsCISROTA,IsCISVZV,IsCDC1,IsCDC4,IsWCC1,IsWCC2,IsWCC3,IsCBP,IsCDC2,IsCDC3,IsCDC7,IsCDC9,IsCDC10,IsMMA1A,
									IsMMA1B,IsMMA2A,IsMMA2B,IsMMA3A,IsMMA3B,IsMMA4A,IsMMA4B,IsIMAMEN,IsIMATD,IsIMAHPV,IsABA,IsAAB,IsAMM1,IsAMM2,IsNCS,IsASM1,IsASM2,IsASM3,IsASM4,IsIMACMB1,IsIMACMB2)	
	SELECT DISTINCT Pvt.CustID as Cust_ID, Pvt.MVDID, Pvt.MemberID, Pvt.PCP_TIN, Pvt.PCP_NPI, Pvt.LOB, pvt.MonthID, 
		   CAST(pvt.W15 as BIT) as IsW15,CAST(pvt.W15_Mod1 as BIT) W15_Mod1,CAST(W34 as BIT) as IsW34,CAST(AWC as BIT) as IsAWC,CAST(LSC as BIT) as IsLSC,CAST(BCS  as BIT)as IsBCS,CAST(CCS  as BIT)as IsCCS,
		   CAST(COL as BIT) as IsCOL,CAST(CAP as BIT) as IsCAP,CAST(ASM as BIT) as IsASM, CAST(CIS as BIT) as IsCIS,CAST(CWP as BIT) as IsCWP,CAST(AMR as BIT) as IsAMR,CAST(AMR_Mod1 as BIT) as IsAMR_Mod1,
		   CAST(FUH7  as BIT)as IsFUH7,CAST(FUH30 as BIT) as IsFUH30,CAST(URI as BIT) as IsURI,CAST(ADD_Init as BIT) as IsADD_Init,CAST(ADD_CM as BIT) as IsADD_CM,CAST(PPC1 as BIT) as IsPPC1,
		   CAST(PPC2  as BIT)as IsPPC2,CAST(CISCMB2 as BIT) as IsCISCMB2,CAST(CISCMB3 as BIT) as IsCISCMB3,CAST(CISCMB4 as BIT) as IsCISCMB4,CAST(CISCMB5 as BIT) as IsCISCMB5,CAST(CISCMB6 as BIT) as IsCISCMB6,
		   CAST(CISCMB7 as BIT) as IsCISCMB7,CAST(CISCMB8 as BIT) as IsCISCMB8,CAST(CISCMB9 as BIT) as IsCISCMB9,CAST(CISCMB10 as BIT) as IsCISCMB10,CAST(CISDTP as BIT) as isCISDTP,CAST(CISHEPA as BIT) as IsCHEPA,
		   CAST(CISHEPB as BIT) as IsCISHEPB,CAST(CISHIB as BIT) as IsCISHIB,CAST(CISINFL as BIT) as IsCISINFL,CAST(CISMMR as BIT) as IsCISMMR,CAST(CISIPV as BIT) as IsCISIPV,CAST(CISPNEU as BIT) as IsCISPNEU,CAST(CISROTA as BIT) as IsCISROTA,
		   CAST(CISVZV as BIT) as IsCISVZV, CAST(CDC1 as BIT) as IsCDC1,CAST(CDC4 as BIT) as IsCDC4,CAST(WCC1 as BIT) as IsWCC1,CAST(WCC2 as BIT) IsWCC2,CAST(WCC3 as BIT) as IsWCC3,CAST(CBP as BIT) as IsCBP,CAST(CDC2 as BIT) as IsCDC2,
		   CAST(CDC3 as BIT) as IsCDC3,CAST(CDC7 as BIT) as IsCDC7,CAST(CDC9 as BIT) as IsCDC9,CAST(CDC10 as BIT) as IsCDC10,CAST(MMA1A as BIT) as IsMMA1A,CAST(MMA1B as BIT) as IsMMA1B,CAST(MMA2A as BIT) as IsMMA2A,
		   CAST(MMA2B as BIT) as IsMMA2B,CAST(MMA3A as BIT) as IsMMA3A,CAST(MMA3B as BIT) as IsMMA3B,CAST(MMA4A as BIT) as IsMMA4A,CAST(MMA4B as BIT) as IsMMA4B,CAST(IMAMEN as BIT) as IsIMAMEN,
		   CAST(IMATD as BIT) as IsIMATD,CAST(IMAHPV as BIT) as IsIMAHPV,CAST(ABA as BIT) as IsABA,CAST(AAB as BIT) as IsAAB,CAST(AMM1 as BIT) as IsAMM1,CAST(AMM2 as BIT) as IsAMM2,CAST(NCS as BIT) as IsNCS,
		   CAST(ASM1 as BIT) as IsASM1,CAST(ASM2 as BIT) as IsASM2,CAST(ASM3 as BIT) as IsASM3,CAST(ASM4 as BIT) as IsASM4,CAST(IMACMB1 as BIT) as IsIMACMB1,CAST(IMACMB2 as BIT) as IsIMACMB2
	 FROM (
	SELECT DISTINCT h.custID, h.MVDID, h.memberid, h.PCP_NPI, h.PCP_TIN, h.LOB , h.monthid, 1 as value, lh.Abbreviation
	FROM Final_HEDIS_Member_FULL h JOIN LookupHEDIS lh on h.TestID = lh.id 
	INNER JOIN HPCustomer C ON C.Cust_ID = h.CustID
	LEFT JOIN Rules.MainPersonalStats R ON R.Cust_ID = h.CustID and R.monthID = h.MonthID and R.MVDID = h.MVDID and R.MemberID = h.MemberID
	where (h.CustID = @CustID or @CustID is NULL) and h.monthID = (Select MAX(h1.MonthID) from Final_HEDIS_Member_FULL h1 Where h1.CustID = h.CustID )  and C.Active = 1 and R.ID is null
		  ) P
	pivot (max(p.value) for Abbreviation in 
		(
			W15,
			W15_Mod1,
			W34,
			AWC,
			LSC,
			BCS,
			CCS,
			COL,
			CAP,
			ASM,
			CIS,
			CWP,
			AMR,
			AMR_Mod1,
			FUH7,
			FUH30,
			URI,
			ADD_Init,
			ADD_CM,
			PPC1,
			PPC2,
			CISCMB2,
			CISCMB3,
			CISCMB4,
			CISCMB5,
			CISCMB6,
			CISCMB7,
			CISCMB8,
			CISCMB9,
			CISCMB10,
			CISDTP,
			CISHEPA,
			CISHEPB,
			CISHIB,
			CISINFL,
			CISMMR,
			CISIPV,
			CISPNEU,
			CISROTA,
			CISVZV,
			CDC1,
			CDC2,
			CDC3,
			CDC4,
			CDC7,
			CDC9,
			CDC10,
			WCC1,
			WCC2,
			WCC3,
			CBP,
			MMA1A,
			MMA1B,
			MMA2A,
			MMA2B,
			MMA3A,
			MMA3B,
			MMA4A,
			MMA4B,
			IMAMEN,
			IMATD,
			IMAHPV,
			ABA,
			AAB,
			AMM1,
			AMM2,
			NCS,
			ASM1,
			ASM2,
			ASM3,
			ASM4,
			IMACMB1,
			IMACMB2
	)) as pvt

END